<?php

namespace Tests\Feature\Routes;

use App\Core\Safety\ManifestBackup;
use App\Core\Safety\SourceOwnershipLock;
use Illuminate\Support\Facades\Route;
use RuntimeException;
use Tests\TestCase;

/**
 * CR-22 — route equivalence, ownership locking and manifest-backed restore.
 *
 * The route-equivalence assertions are the gate for any future route change:
 * order is behaviour, so the ORDERED signature must match, not merely the set.
 */
class RouteEquivalenceTest extends TestCase
{
    private const BASELINE = '/root/cr22-baseline-20260727';

    /**
     * BASELINE SUPERSEDED — ENTERPRISE888 E1 M0 (2026-07-27)
     * One READ-ONLY endpoint was added: GET api/admin/engineering/manifest.
     * Verified: exactly 1 added route, 0 removed, 0 altered; count 982 -> 983.
     * A signature change is never waived as noise — this one is recorded and
     * justified. See BASELINE-NOTE-E1M0.md.
 Generated by the SAME generator as the live signature — see route_signature.php. */
    private const CANON = '/root/cr22-baseline-20260727/canonical';

    /** Normalised, ordered signature of the live route table. */
    private function signature(): array
    {
        $rows = [];
        foreach (Route::getRoutes()->getRoutes() as $r) {
            $mw = $r->gatherMiddleware();
            sort($mw);
            $rows[] = implode('|', [
                implode(',', $r->methods()),
                $r->uri(),
                (string) $r->getName(),
                (string) $r->getActionName(),
                (string) $r->getDomain(),
                implode(',', $mw),
            ]);
        }

        return $rows;
    }

    // ── route equivalence ────────────────────────────────────────────────────

    /** @test The live route table still has exactly the baseline count. */
    public function the_route_count_matches_the_baseline(): void
    {
        $file = self::CANON . '.ordered.txt';
        if (!is_file($file)) {
            $this->markTestSkipped('canonical baseline not present on this host');
        }
        $baselineCount = count(array_filter(explode("\n", trim((string) file_get_contents($file)))));

        $this->assertSame($baselineCount, count($this->signature()),
            'the number of registered routes changed — route count is a hard gate');
    }

    /** @test Order is behaviour: first-registered wins a collision. */
    public function the_ordered_route_signature_is_unchanged(): void
    {
        $file = self::CANON . '.ordered.txt';
        if (!is_file($file)) {
            $this->markTestSkipped('canonical baseline not present on this host');
        }
        // Same generator on both sides, so any difference here is REAL.
        $baseline = array_filter(explode("\n", trim((string) file_get_contents($file))));
        $baseline = array_values($baseline);
        $live = $this->signature();

        $this->assertSame(count($baseline), count($live), 'route count differs');

        foreach ($baseline as $i => $expected) {
            $this->assertSame($expected, $live[$i],
                "route order or metadata changed at position {$i}. Order is behaviour — "
                . 'a difference here is never waived as serialization noise.');
        }
    }

    /** @test No route lost its middleware — an auth bypass would look like this. */
    public function no_route_lost_its_middleware(): void
    {
        $naked = [];
        foreach (Route::getRoutes()->getRoutes() as $r) {
            $uri = $r->uri();
            if (!str_starts_with($uri, 'api/')) {
                continue;
            }
            if (str_starts_with($uri, 'api/public/') || $uri === 'api/health') {
                continue;   // intentionally unauthenticated
            }
            $mw = $r->gatherMiddleware();
            $hasAuth = (bool) array_filter($mw, fn ($m) => str_contains(strtolower((string) $m), 'auth')
                || str_contains(strtolower((string) $m), 'apikey'));
            if (!$hasAuth) {
                $naked[] = implode(',', $r->methods()) . ' ' . $uri;
            }
        }

        // Recorded as a baseline count rather than asserted to zero: some legacy
        // routes are legitimately open, and CR-22 must not "improve" them.
        // Measured baseline: 88 api routes are legitimately unauthenticated
        // (auth endpoints, oauth callbacks, health, public widget). CR-22 must
        // NOT "improve" them — this pins the number so it cannot GROW unnoticed.
        $this->assertLessThanOrEqual(88, count($naked),
            'the number of api routes without an auth-ish middleware grew: ' . implode(', ', array_slice($naked, 0, 10)));
    }

    // ── source ownership locking ─────────────────────────────────────────────

    /** @test A second session cannot take a live lock. */
    public function a_second_owner_is_refused(): void
    {
        $lock = new SourceOwnershipLock(sys_get_temp_dir() . '/cr22locks-' . uniqid());
        $lock->acquire('routes-api', 'session-A', 'CR-22', ['/tmp/x']);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/owned by session-A/');
        $lock->acquire('routes-api', 'session-B', 'PhaseQ', ['/tmp/x']);
    }

    /** @test The same owner is re-entrant. */
    public function the_same_owner_may_re_acquire(): void
    {
        $lock = new SourceOwnershipLock(sys_get_temp_dir() . '/cr22locks-' . uniqid());
        $lock->acquire('routes-api', 'session-A', 'CR-22', ['/tmp/x']);
        $again = $lock->acquire('routes-api', 'session-A', 'CR-22', ['/tmp/x']);

        $this->assertSame('session-A', $again['owner']);
    }

    /** @test Writing without a lock fails closed. */
    public function writing_without_a_lock_is_refused(): void
    {
        $lock = new SourceOwnershipLock(sys_get_temp_dir() . '/cr22locks-' . uniqid());

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/no ownership lock/');
        $lock->assertOwned('routes-api', 'session-A');
    }

    /** @test A non-owner is refused — the INC-2026-003 condition. */
    public function a_non_owner_cannot_assert_ownership(): void
    {
        $lock = new SourceOwnershipLock(sys_get_temp_dir() . '/cr22locks-' . uniqid());
        $lock->acquire('routes-api', 'session-A', 'CR-22', ['/tmp/x']);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/INC-2026-003/');
        $lock->assertOwned('routes-api', 'session-B');
    }

    /** @test Release records which owned paths actually changed. */
    public function release_records_what_changed(): void
    {
        $dir = sys_get_temp_dir() . '/cr22locks-' . uniqid();
        $file = sys_get_temp_dir() . '/cr22-owned-' . uniqid() . '.txt';
        file_put_contents($file, 'before');

        $lock = new SourceOwnershipLock($dir);
        $lock->acquire('routes-api', 'session-A', 'CR-22', [$file]);
        file_put_contents($file, 'after');
        $res = $lock->release('routes-api', 'session-A');

        $this->assertTrue($res['released']);
        $this->assertContains($file, $res['changed_paths']);
        @unlink($file);
    }

    // ── manifest-backed backup / restore ─────────────────────────────────────

    /** @test A snapshot without a manifest is not restorable. */
    public function a_backup_without_a_manifest_is_refused(): void
    {
        $dir = sys_get_temp_dir() . '/cr22snap-' . uniqid();
        mkdir($dir, 0775, true);

        $b = new ManifestBackup($dir);
        $eval = $b->evaluateRestore($dir);

        $this->assertFalse($eval['allowed']);
        $this->assertStringContainsString('NO_MANIFEST', $eval['reasons'][0]);
    }

    /**
     * @test THE INC-2026-003 SCENARIO — a stale snapshot cannot overwrite newer work.
     */
    public function a_stale_snapshot_cannot_revert_newer_work(): void
    {
        $root = sys_get_temp_dir() . '/cr22bk-' . uniqid();
        $file = sys_get_temp_dir() . '/cr22-routes-' . uniqid() . '.php';
        file_put_contents($file, "<?php // version 1 — before three phases of fixes\n");

        $b = new ManifestBackup($root);
        $snap = $b->capture([$file], 'phaseP', 'session-P', 'PhaseP');

        // Three phases of fixes land afterwards.
        file_put_contents($file, "<?php // version 2 — P1 + P2-A + P2-B fixes applied\n");

        $eval = $b->evaluateRestore($snap['dir'], [$file]);

        $this->assertFalse($eval['allowed'],
            'a snapshot taken before newer work must not be restorable — this IS INC-2026-003');
        $this->assertContains($file, $eval['changed_since']);
        $this->assertStringContainsString('SOURCE_HAS_ADVANCED', $eval['reasons'][0]);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/RESTORE REFUSED/');
        $b->restore($snap['dir'], [$file], 'session-P');
    }

    /** @test A legitimate restore of unchanged source is allowed. */
    public function a_current_snapshot_restores_cleanly(): void
    {
        $root = sys_get_temp_dir() . '/cr22bk-' . uniqid();
        $file = sys_get_temp_dir() . '/cr22-routes-' . uniqid() . '.php';
        file_put_contents($file, "<?php // current\n");

        $b = new ManifestBackup($root);
        $snap = $b->capture([$file], 'current', 'session-A', 'CR-22');

        $eval = $b->evaluateRestore($snap['dir'], [$file]);
        $this->assertTrue($eval['allowed'], implode('; ', $eval['reasons']));

        file_put_contents($file, "<?php // accidental damage\n");
        // The snapshot is now stale by definition, so a deliberate override is
        // required — which is correct: the operator must confirm the revert.
        $b->restore($snap['dir'], [$file], 'session-A', true);
        $this->assertStringContainsString('current', (string) file_get_contents($file));
        @unlink($file);
    }

    /** @test A restore may not silently touch files the caller did not name. */
    public function a_restore_may_not_touch_unrelated_modules(): void
    {
        $root = sys_get_temp_dir() . '/cr22bk-' . uniqid();
        $a = sys_get_temp_dir() . '/cr22-a-' . uniqid() . '.php';
        $c = sys_get_temp_dir() . '/cr22-b-' . uniqid() . '.php';
        file_put_contents($a, 'A');
        file_put_contents($c, 'B');

        $b = new ManifestBackup($root);
        $snap = $b->capture([$a, $c], 'both', 'session-A', 'CR-22');

        $eval = $b->evaluateRestore($snap['dir'], [$a]);   // ask for only one

        $this->assertFalse($eval['allowed']);
        $this->assertStringContainsString('WOULD_TOUCH_UNRELATED', implode(' ', $eval['reasons']));
        @unlink($a);
        @unlink($c);
    }

    /** @test A manifest records the evidence needed to judge a restore. */
    public function a_manifest_records_hashes_and_provenance(): void
    {
        $root = sys_get_temp_dir() . '/cr22bk-' . uniqid();
        $file = sys_get_temp_dir() . '/cr22-m-' . uniqid() . '.php';
        file_put_contents($file, '<?php');

        /*
         * This asserts that capture() ROUND-TRIPS what it is given. It is not a
         * statement about the live route count, so it must not carry a literal
         * that needs updating on every approved route change — twice now, a
         * blanket re-baseline has moved the assertion and left the fixture
         * behind, failing for a reason that had nothing to do with the code
         * under test. The value is a variable so the two can never disagree.
         */
        $routeCount = 12345;

        $b = new ManifestBackup($root);
        $snap = $b->capture([$file], 'evidence', 'session-A', 'CR-22', [
            'route_count' => $routeCount,
            'route_signature_sha256' => 'abc',
            'phase_markers' => ['phase_o' => 2, 'phase_p' => 1],
        ]);

        $m = $snap['manifest'];
        $this->assertSame('session-A', $m['owner']);
        $this->assertSame($routeCount, $m['route_count']);
        $this->assertSame('abc', $m['route_signature_sha256']);
        $this->assertSame(2, $m['phase_markers']['phase_o']);
        $this->assertNotEmpty($m['files'][$file]['sha256']);
        $this->assertNotEmpty($m['captured_at']);
        @unlink($file);
    }
}
