<?php

namespace App\Engines\Builder\Support;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * SITE THUMBNAIL (2026-09-15, Owner: "on website page, website is not showing thumbnail image … convert to low res …
 * proper caching"). A 480x300 JPEG (tens of KB) of the exported home page, stored under
 * storage/app/public/site-thumbs/{id}.jpg and recorded on websites.thumbnail_url with a version stamp (?v=mtime) so the
 * browser may cache it for good and still sees a fresh shot after a deploy. Generated by GenerateSiteThumbnailJob after
 * every deploy (debounced) and by `sites:thumbnails` for backfill.
 */
final class SiteThumbnail
{
    public const DIR = 'site-thumbs';

    public static function generate(int $websiteId): ?string
    {
        $export = storage_path("app/public/sites/{$websiteId}/index.html");
        if (! is_file($export)) { return null; }
        $dir = storage_path('app/public/' . self::DIR);
        if (! is_dir($dir)) { @mkdir($dir, 0775, true); }
        $out = "{$dir}/{$websiteId}.jpg";
        $tmp = "{$dir}/{$websiteId}.tmp.jpg";
        $url = rtrim((string) config('app.url'), '/') . "/storage/sites/{$websiteId}/index.html?thumb=" . time();
        $tool = base_path('tools/site-thumb.cjs');
        @unlink($tmp);   // a leftover from an interrupted render (possibly another user's) must not block this one
        $cmd = 'HOME=/tmp PUPPETEER_CACHE_DIR=' . escapeshellarg(base_path('.puppeteer-cache')) . ' timeout 90 node '
             . escapeshellarg($tool) . ' ' . escapeshellarg($url) . ' ' . escapeshellarg($tmp) . ' 2>&1';
        exec($cmd, $output, $rc);
        if ($rc !== 0 || ! is_file($tmp) || filesize($tmp) < 600) {   // a solid-colour page compresses to ~1 KB and is still a true shot
            Log::warning('[SiteThumbnail] render failed', ['website' => $websiteId, 'rc' => $rc, 'out' => implode(' | ', array_slice($output, -3))]);
            @unlink($tmp);
            return null;
        }
        @rename($tmp, $out);
        @chmod($out, 0664);
        // the scheduler runs as root: hand the file to www-data so workers and commands can overwrite it later
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) { @chown($out, 'www-data'); @chgrp($out, 'www-data'); }
        $publicUrl = '/storage/' . self::DIR . "/{$websiteId}.jpg?v=" . filemtime($out);
        DB::table('websites')->where('id', $websiteId)->update(['thumbnail_url' => $publicUrl]);
        return $publicUrl;
    }
}
