<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('aeo_settings', function (Blueprint $t) {
            $t->unsignedBigInteger('workspace_id')->primary();
            // AI crawler allow/block (default: allow the major ones,
            // block Bytespider which is TikTok's scraper).
            $t->boolean('aeo_mode_enabled')->default(true);
            $t->boolean('allow_gptbot')->default(true);
            $t->boolean('allow_claudebot')->default(true);
            $t->boolean('allow_perplexitybot')->default(true);
            $t->boolean('allow_bingbot')->default(true);
            $t->boolean('allow_google_extended')->default(true);
            $t->boolean('allow_bytespider')->default(false);
            $t->boolean('allow_amazonbot')->default(true);
            $t->boolean('allow_ccbot')->default(true);
            // llms.txt cache — regenerated by daily cron + on-demand
            $t->longText('llms_txt_cache')->nullable();
            $t->timestamp('llms_txt_regen_at')->nullable();
            $t->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('aeo_settings');
    }
};
