<?php
declare(strict_types=1);
/**
 * Competitor facts for /compare. Every figure carries its source and the month it was verified (masterplan §02,
 * researched 7 September 2026). Re-verify quarterly; the page prints the date so a stale figure is visibly stale.
 */
return [
    'verified' => 'September 2026',
    'competitors' => [
        ['slug' => 'wix', 'name' => 'Wix', 'camp' => 'Website builder', 'entry' => '$17/mo billed annually', 'top' => '$29 · $39 · $159/mo', 'sells' => 'A site with storage tiers, ecommerce from the Business plan, AI text tools on every plan, 24/7 care.', 'thin' => 'No workforce operating the business after the site is built; CRM and email are add-ons; monthly billing costs up to 41% more than the advertised annual price.', 'sources' => ['https://www.websitebuilderexpert.com/website-builders/wix-pricing/', 'https://www.forbes.com/advisor/business/wix-pricing/']],
        ['slug' => 'hostinger', 'name' => 'Hostinger', 'camp' => 'Website builder', 'entry' => '$2.99/mo on a 48-month term', 'top' => '$11.99/mo monthly · renews at $10.99/mo', 'sells' => 'An AI-built site, hosting, a free domain for the first year, SSL.', 'thin' => 'The headline price needs a four-year commitment and renews higher; nothing runs the business after launch.', 'sources' => ['https://tech.co/website-builders/hostinger-website-builder-pricing', 'https://www.sitebuilderreport.com/hostinger-website-builder-pricing']],
        ['slug' => 'godaddy-airo', 'name' => 'GoDaddy Airo', 'camp' => 'Website builder and domain', 'entry' => 'about $9.99 to $11.99/mo in year one', 'top' => 'Airo Plus $4.99/mo, renewing at $95.88/yr', 'sells' => 'Site, email and newsletter generation, AI SEO suggestions, web chat.', 'thin' => 'US and Canada only; renewal increases of about 60%; AI is a layer on a domain business.', 'sources' => ['https://hostadvice.com/hosting-company/godaddy-reviews/airo-pricing/', 'https://www.saasgenius.com/reviews/godaddy-airo-pricing/']],
        ['slug' => '10web', 'name' => '10Web', 'camp' => 'WordPress AI builder', 'entry' => 'Free · $30/mo', 'top' => '$45 · $60/mo · Enterprise', 'sells' => 'AI-generated WordPress sites with hosting, metered by visitors and AI words.', 'thin' => 'Metering on words and visitors; no CRM, no workforce, WordPress maintenance is yours.', 'sources' => ['https://www.capterra.com/p/186678/10Web/pricing/', 'https://rovela.ai/blog/10web-pricing-plans']],
        ['slug' => 'durable', 'name' => 'Durable', 'camp' => 'AI site with light business tools', 'entry' => 'Free · $22 to $25/mo', 'top' => '$85 to $99/mo', 'sells' => 'Site, hosting, a basic CRM, invoicing, bookings, blog, SEO, image generation, a 30-day money-back guarantee.', 'thin' => 'Single-site, solo-operator scope; no agents, no agency tier, no video.', 'sources' => ['https://website-builders.cybernews.com/durable-ai-website-builder-review/', 'https://www.toolworthy.ai/tool/durable']],
        ['slug' => 'b12', 'name' => 'B12', 'camp' => 'AI site with client engagement', 'entry' => '$49/mo ($42 annually)', 'top' => '$78 · $199 plus a $1,999 setup fee · $399/mo', 'sells' => 'Site, scheduling, payments, email marketing, AI credits, done-with-you setup.', 'thin' => 'Setup fees at the professional tier; built for services firms, not for multi-site or agencies.', 'sources' => ['https://www.b12.io/pricing/', 'https://cybernaira.com/b12-ai-pricing/']],
        ['slug' => 'hubspot-starter', 'name' => 'HubSpot Starter', 'camp' => 'CRM platform', 'entry' => '$20 per seat per month list, $7 promotional annual', 'top' => 'Professional tiers from several hundred dollars a month', 'sells' => 'Five hubs at Starter level, 500 credits, Breeze AI agents.', 'thin' => 'Per-seat metering, no site you own, and a well-documented price cliff from Starter to Professional.', 'sources' => ['https://www.hubspot.com/products/crm/starter', 'https://www.getpricepulse.com/companies/hubspot-pricing.html']],
        ['slug' => 'gohighlevel', 'name' => 'GoHighLevel', 'camp' => 'Agency platform', 'entry' => '$97/mo', 'top' => '$297 unlimited · $497 SaaS mode', 'sells' => 'White-label CRM, funnels, automations, unlimited sub-accounts, a resell mode.', 'thin' => 'Agency-only and complex; no AI workforce; no owned site product for the end business.', 'sources' => ['https://getautomized.com/gohighlevel-pricing/', 'https://ghlexpertly.com/gohighlevel-white-label-pricing']],
        ['slug' => 'markty', 'name' => 'Markty', 'camp' => 'AI employees', 'entry' => '$45/mo ($22 annually)', 'top' => '$200/mo · custom', 'sells' => 'Role-based marketing agents, AI-search visibility, review management, autonomous publishing.', 'thin' => 'No website, no domain, no CRM you own; the brand\'s assets live somewhere else.', 'sources' => ['https://www.capterra.com/p/10038947/Markty/', 'https://www.eesel.ai/blog/markty-ai-alternatives']],
        ['slug' => 'sintra', 'name' => 'Sintra', 'camp' => 'AI helpers', 'entry' => '$15.60 to $48.50/mo', 'top' => 'All twelve helpers on one plan', 'sells' => 'Twelve chat helpers, 250 credits a month, integrations.', 'thin' => 'Credits reported to run out within days; helpers advise, they do not operate assets.', 'sources' => ['https://sintra.ai/pricing', 'https://socialrails.com/blog/sintra-ai-pricing']],
    ],
];
