<?php
/*
 * INDUSTRY-KIT-1 (Owner 2026-10-06: every industry page shows "whatever is dedicated catalog and lead capture for that
 * industry. Example appointment booking system + property listing"). The facts come from the platform's own catalogue registry
 * (app/Engines/Builder/Support/CatalogueKinds.php, DEC-0049) and the public-site capture paths (POST /book on every published
 * site, contact forms, catalogue item enquiries, the website chatbot, social comment leads). Nothing here is claimed that the
 * platform does not do; the copy says what the owner gets, never how it is built.
 *
 *   catalogue  [plural label, singular, item button, has detail pages, status words, example items [[title, meta, price|null, status]]]
 *   book       the booking button as the website shows it
 *   detail     one line on what the detail pages hold ('' = no detail pages)
 */
return [
    'restaurant'         => ['catalogue' => ['Menu', 'dish', 'Order', false, 'On the menu · Sold out', [['Roast cod, brown butter', 'Main · Bestseller', '£24', 'On the menu'], ['Burrata, blood orange', 'Starter', '£12', 'On the menu'], ['Chocolate tart', 'Dessert', '£9', 'Sold out']]], 'book' => 'Book a table', 'detail' => ''],
    'cafe'               => ['catalogue' => ['Menu', 'item', 'Order', false, 'On the menu · Sold out', [['Flat white', 'Coffee', '£3.40', 'On the menu'], ['Cardamom bun', 'Pastry · Bestseller', '£3.80', 'On the menu'], ['Sourdough loaf', 'Bread · Saturdays', '£5', 'Sold out']]], 'book' => 'Book a table', 'detail' => ''],
    'catering'           => ['catalogue' => ['Packages', 'package', 'Enquire', false, 'Available', [['Wedding feast', 'From 60 guests · 3 courses', 'From £68 pp', 'Available'], ['Office lunch', '12 to 200 · delivered', 'From £14 pp', 'Available'], ['Canapé evening', 'Reception · 2 hours', 'From £22 pp', 'Available']]], 'book' => 'Request a quote', 'detail' => ''],
    'retail_shop'        => ['catalogue' => ['Products', 'product', 'Enquire', false, 'Available', [['Linen apron', 'Kitchen · Bestseller', '£38', 'Available'], ['Hand-thrown mug', 'Tableware', '£24', 'Available'], ['Gift card', 'Any amount', null, 'Available']]], 'book' => 'Visit us', 'detail' => ''],
    'ecommerce'          => ['catalogue' => ['Products', 'product', 'Enquire', false, 'Available', [['Field jacket', 'Outerwear · New', '£145', 'Available'], ['Canvas tote', 'Bags', '£32', 'Available'], ['Wool beanie', 'Accessories', '£28', 'Available']]], 'book' => 'Ask a question', 'detail' => ''],
    'aesthetic_clinic'   => ['catalogue' => ['Treatments', 'treatment', 'Enquire', false, 'Available', [['Skin consultation', '30 min', 'Free', 'Available'], ['Anti-wrinkle treatment', '45 min', 'From £180', 'Available'], ['Laser hair removal', 'Course of 6', 'From £340', 'Available']]], 'book' => 'Book a consultation', 'detail' => ''],
    'beauty_salon'       => ['catalogue' => ['Treatments', 'treatment', 'Enquire', false, 'Available', [['Cut and finish', '60 min', 'From £48', 'Available'], ['Full balayage', '180 min', 'From £140', 'Available'], ['Gel manicure', '45 min', '£32', 'Available']]], 'book' => 'Book an appointment', 'detail' => ''],
    'barbershop'         => ['catalogue' => ['Services and prices', 'service', 'Enquire', false, 'Available', [['Skin fade', '30 min', '£22', 'Available'], ['Beard trim and shape', '20 min', '£14', 'Available'], ['Hot towel shave', '40 min', '£28', 'Available']]], 'book' => 'Book a chair', 'detail' => ''],
    'dental'             => ['catalogue' => ['Treatments', 'treatment', 'Enquire', false, 'Available', [['New patient exam', '40 min · includes X-rays', '£65', 'Available'], ['Hygienist visit', '30 min', '£72', 'Available'], ['Invisible aligners', 'Consultation first', 'From £1,900', 'Available']]], 'book' => 'Book an appointment', 'detail' => ''],
    'medical_clinic'     => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['GP consultation', '20 min · same week', '£85', 'Available'], ['Blood tests', 'Results in 48 h', 'From £45', 'Available'], ['Travel vaccinations', 'Nurse-led', 'From £30', 'Available']]], 'book' => 'Book an appointment', 'detail' => ''],
    'online_courses'     => ['catalogue' => ['Courses', 'course', 'Enquire', false, 'Open · Full', [['Foundations of UX', '6 weeks · self-paced', '£290', 'Open'], ['Portfolio sprint', '2 weeks · live', '£180', 'Full'], ['Mentoring pack', '4 calls', '£240', 'Open']]], 'book' => 'Book a call', 'detail' => ''],
    'tutoring'           => ['catalogue' => ['Courses', 'course', 'Enquire', false, 'Open · Full', [['GCSE Maths', 'Weekly · 1 to 1', '£38 / hour', 'Open'], ['A-level Chemistry', 'Weekly · small group', '£26 / hour', 'Open'], ['11+ preparation', 'Saturday mornings', '£30 / hour', 'Full']]], 'book' => 'Book a free assessment', 'detail' => ''],
    'training_center'    => ['catalogue' => ['Courses', 'course', 'Enquire', false, 'Open · Full', [['Forklift licence', '3 days · certified', '£395', 'Open'], ['First aid at work', '3 days', '£260', 'Open'], ['IOSH Managing Safely', '4 days', '£540', 'Full']]], 'book' => 'Reserve a place', 'detail' => ''],
    'hotel'              => ['catalogue' => ['Rooms and rates', 'room', 'Reserve', true, 'Available', [['Harbour Suite', '42 sqm · Sleeps 2 · Sea view', 'From £240', 'Available'], ['Classic Double', '24 sqm · Sleeps 2', 'From £150', 'Available'], ['Family Room', '36 sqm · Sleeps 4', 'From £210', 'Available']]], 'book' => 'Check availability', 'detail' => 'Each room has its own page with photos, size, view and what is included.'],
    'resort'             => ['catalogue' => ['Rooms and rates', 'room', 'Reserve', true, 'Available', [['Beachfront Villa', '110 sqm · Sleeps 4 · Private pool', 'From £620', 'Available'], ['Garden Suite', '55 sqm · Sleeps 2', 'From £310', 'Available'], ['Spa Residence', '70 sqm · Sleeps 2 · Spa access', 'From £390', 'Available']]], 'book' => 'Check availability', 'detail' => 'Each villa and suite has its own page with photos, size, view and what is included.'],
    'short_term_rental'  => ['catalogue' => ['Rentals', 'rental', 'Reserve', true, 'Available', [['The Harbour Loft', 'Sleeps 4 · 2 bed · Parking', 'From £165 / night', 'Available'], ['Swallow Barn', 'Sleeps 6 · 3 bed · Dog friendly', 'From £220 / night', 'Available'], ['Wrens Cottage', 'Sleeps 2 · Log burner', 'From £120 / night', 'Available']]], 'book' => 'Check dates', 'detail' => 'Each property has its own page with photos, sleeps, bedrooms and what is included.'],
    'gym'                => ['catalogue' => ['Programmes and memberships', 'programme', 'Enquire', false, 'Open · Full', [['Strength foundations', '8 weeks · coached', '£180', 'Open'], ['Unlimited membership', 'Monthly · all classes', '£79 / month', 'Open'], ['6 am small group', 'Mon, Wed, Fri', '£120 / month', 'Full']]], 'book' => 'Book a free trial', 'detail' => ''],
    'travel_agency'      => ['catalogue' => ['Packages', 'package', 'Book now', false, 'Available · Sold out', [['Amalfi slow week', '7 nights · Naples · May to Oct', 'From £1,480 pp', 'Available'], ['Kyoto in autumn', '10 nights · Osaka · Nov', 'From £2,950 pp', 'Available'], ['Lake District weekend', '3 nights · guided', 'From £540 pp', 'Sold out']]], 'book' => 'Plan my trip', 'detail' => ''],
    'event_venue'        => ['catalogue' => ['Packages and past events', 'package', 'Enquire', false, 'Available', [['Weekend wedding', 'Up to 140 · exclusive use', 'From £9,800', 'Available'], ['Corporate day', '40 to 200 · AV included', 'From £75 pp', 'Available'], ['Private dinner', 'The Long Gallery · 30', 'From £1,900', 'Available']]], 'book' => 'Check a date', 'detail' => ''],
    'childcare'          => ['catalogue' => ['Programmes', 'programme', 'Enquire', false, 'Open · Full', [['Baby room', '3 months to 2 years', 'From £68 / day', 'Full'], ['Toddlers', '2 to 3 years', 'From £64 / day', 'Open'], ['Pre-school', '3 to 5 years · funded hours', 'From £58 / day', 'Open']]], 'book' => 'Book a visit', 'detail' => ''],
    'pet_services'       => ['catalogue' => ['Services and prices', 'service', 'Enquire', false, 'Available', [['Full groom', 'Small dog · 90 min', 'From £42', 'Available'], ['Day care', 'Full day · collected by 6', '£32', 'Available'], ['Boarding', 'Per night · walks included', 'From £38', 'Available']]], 'book' => 'Book a slot', 'detail' => ''],
    'home_services'      => ['catalogue' => ['Services and prices', 'service', 'Enquire', false, 'Available', [['Boiler service', 'Annual · certificate', '£89', 'Available'], ['Emergency call-out', 'Same day', 'From £120', 'Available'], ['Bathroom refit', 'Quoted on site', null, 'Available']]], 'book' => 'Request a quote', 'detail' => ''],
    'automotive'         => ['catalogue' => ['Services and prices', 'service', 'Enquire', false, 'Available', [['MOT', '45 min · while you wait', '£54.85', 'Available'], ['Full service', 'From 2 hours', 'From £189', 'Available'], ['Diagnostics', 'Fault code read', '£60', 'Available']]], 'book' => 'Book your car in', 'detail' => ''],
    'consulting'         => ['catalogue' => ['Services and case studies', 'service', 'Enquire', true, 'Available', [['Strategy sprint', '4 weeks · leadership team', 'From £12,000', 'Available'], ['Operating model review', '8 weeks', 'Scoped', 'Available'], ['Board advisory', 'Retainer', 'Monthly', 'Available']]], 'book' => 'Book a call', 'detail' => 'Case studies have their own pages: the client, the brief, the work and the result.'],
    'marketing_agency'   => ['catalogue' => ['Services and case studies', 'service', 'Enquire', true, 'Available', [['Brand and launch', '6 weeks', 'From £9,500', 'Available'], ['Paid media management', 'Monthly', 'From £1,800 / month', 'Available'], ['SEO programme', 'Quarterly', 'From £2,400 / month', 'Available']]], 'book' => 'Book a call', 'detail' => 'Case studies have their own pages: the client, the brief, the work and the result.'],
    'it_services'        => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Managed IT', 'Per user · monthly', 'From £45 / user', 'Available'], ['Cyber essentials', 'Certification in 30 days', 'From £1,200', 'Available'], ['Cloud migration', 'Scoped', null, 'Available']]], 'book' => 'Book a call', 'detail' => ''],
    'architecture'       => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Feasibility study', '2 to 3 weeks', 'From £1,500', 'Available'], ['Planning application', 'Drawings and submission', 'From £4,800', 'Available'], ['Full design service', 'RIBA stages 1 to 6', 'Percentage of build', 'Available']]], 'book' => 'Book a consultation', 'detail' => ''],
    'construction'       => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Extensions', 'Single and double storey', 'Quoted', 'Available'], ['Loft conversions', 'Design to completion', 'Quoted', 'Available'], ['Commercial fit-out', 'Offices and retail', 'Quoted', 'Available']]], 'book' => 'Request a quote', 'detail' => ''],
    'interior_design'    => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Room scheme', 'One room · 2 weeks', 'From £900', 'Available'], ['Whole home', 'Design and sourcing', 'From £6,500', 'Available'], ['Project management', 'On site', 'Percentage of spend', 'Available']]], 'book' => 'Book a consultation', 'detail' => ''],
    'real_estate_agency' => ['catalogue' => ['Properties', 'property', 'View details', true, 'For sale · To let · Under offer · Sold · Let', [['Harbour District townhouse', '4 bed · 3 bath · 2,100 sq ft', '£1,250,000', 'For sale'], ['Riverside apartment', '2 bed · 2 bath · 980 sq ft', '£2,400 pcm', 'To let'], ['Millgate farmhouse', '5 bed · 4 bath · 3,400 sq ft', '£1,890,000', 'Under offer']]], 'book' => 'Request a valuation', 'detail' => 'Every property has its own page with photos, beds, baths, size and location, and sold or let properties move to a Recently sold and let section on their own.'],
    'legal'              => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Conveyancing', 'Fixed fee · residential', 'From £950', 'Available'], ['Wills and probate', 'Fixed fee', 'From £240', 'Available'], ['Employment advice', 'Hourly', '£220 / hour', 'Available']]], 'book' => 'Book a consultation', 'detail' => ''],
    'accounting'         => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Year-end accounts', 'Limited company', 'From £890', 'Available'], ['Bookkeeping', 'Monthly', 'From £120 / month', 'Available'], ['Self-assessment', 'Fixed fee', 'From £180', 'Available']]], 'book' => 'Book a call', 'detail' => ''],
    'news_channel'       => ['catalogue' => ['Services', 'service', 'Enquire', false, 'Available', [['Display advertising', 'Weekly · homepage', 'From £180 / week', 'Available'], ['Sponsored feature', '800 words · shared', 'From £450', 'Available'], ['Newsletter sponsor', '12,000 readers', 'From £300', 'Available']]], 'book' => 'Advertise with us', 'detail' => ''],
];
