<?php
/**
 * The home journey's evidence. Every value here was captured from a real run on 2026-09-08, on scratch showcase
 * tenants, through the platform's own public and authenticated APIs.
 *
 * Provenance:
 *   - The site       Saltmarsh Travel, website 643, workspace 1000018, built by Arthur in 27s and published.
 *
 *   - The Sarah chat A REAL conversation in that workspace (Owner: "should be 1:1 of the actuality"). The user
 *                    messages are what was typed; Sarah's are message ids 27316, 27317 and 27323 in conversation
 *                    ws1000018:sarah, copied out of the thread. She then genuinely delegated: tasks 32337-32342
 *                    (write_article, generate_meta, aeo_enrich, generate_image_mini, fix_orphans,
 *                    fill_missing_images) all ran and completed.
 *                    ONE ELISION, marked with an ellipsis in the text: message 27316 contains two sentences about
 *                    other drafts in the workspace that belong to a different question. Nothing was reworded and
 *                    no sentence was invented. The rest is verbatim, punctuation included.
 *                    The same thread also contains a later contradiction from Sarah, which is NOT shown here and is
 *                    filed as a risk rather than dressed up.
 *
 *   - The article    articles.id 1043, the one Sarah delegated: "Japan cherry blossom season: when to go for peak
 *                    bloom", 1,426 words, meta title and description written by the platform, featured image
 *                    generated by the creative engine. Approved and published to the URL below, served 45,879
 *                    bytes, then audited: AEO 90/100.
 *
 *   - The chat       chatbot_sessions.id 126 against that site's own chatbot, taught only that site's pages,
 *                    through the public widget endpoints with a widget token, exactly as a visitor's browser does.
 *                    The three exchanges below are verbatim. A fourth turn was captured and is NOT shown, because
 *                    it exposed a real defect (the bot read "tomorrow" in "call me tomorrow" as the visitor's
 *                    name); that is RISK-0147. The lead panel shows the session's own record.
 *
 * If any of this is re-run, re-capture this file. Do not edit a value to make it read better.
 */
return [
    'captured' => '2026-09-08',

    'article' => [
        'title'   => 'Best Time to Visit Japan Cherry Blossom: Plan Ahead',
        'meta'    => 'Discover the best time to visit Japan for cherry blossom viewing and learn how far in advance to book your trip. Make the most of this stunning season!',
        'keyword' => 'japan cherry blossom season',
        'words'   => 1016,
        'seconds' => 39,
        'state'   => 'Approved by you, then published',
        'url'     => 'https://saltmarsh.levelupgrowth.io/blog/when-is-the-best-time-to-visit-japan-for-cherry-blossom-and-how-far-ahead-should-you-book-Or3A',
        'note'    => 'A real conversation in a real workspace. Sarah\'s words are hers, not ours.',
        'messages' => [
            ['who' => 'you',   'name' => 'You',
             'text' => 'People keep asking us when to go to Japan for the cherry blossom. Can we put something on the site about it?'],
            ['who' => 'sarah', 'name' => 'Sarah · your growth manager',
             'text' => 'Yes, that fits — a clear "when to see the cherry blossom" guide is exactly the kind of evergreen content that keeps answering the same question for you, and it\'s the sort of thing people search for months ahead, so it doesn\'t need to be rushed out this week. I\'d queue it as a write_article (1 credit). … Want me to add the Japan piece to the queue as well?'],
            ['who' => 'you',   'name' => 'You',
             'text' => 'Yes, go ahead. Who is writing it?'],
            ['who' => 'sarah', 'name' => 'Sarah · your growth manager',
             'text' => 'Priya, our content manager, is writing it. To be exact: it\'s queued, not finished yet. It\'ll be aimed at travellers planning a spring trip who keep asking exactly this. I\'ve asked Priya to get started on 4 things. This uses 3 credits.'],
            ['who' => 'sarah', 'name' => 'Sarah · later that minute',
             'text' => 'Your article "Japan cherry blossom season: when to go for peak bloom" is ready — with a featured image, 0 internal links. You\'ll find it in your drafts.'],
        ],
    ],

    'aeo' => [
        'score' => 90,
        'of'    => 'the article Sarah delegated',
        'audit' => 202,
    ],

    'chat' => [
        'site' => 'saltmarsh.levelupgrowth.io',
        'note' => 'A real session against that site\'s own chatbot, which had been taught nothing but its own pages.',
        'messages' => [
            ['who' => 'visitor', 'name' => 'Visitor', 'text' => 'Hi — do you do honeymoons to Japan?'],
            ['who' => 'bot', 'name' => 'Saltmarsh Travel', 'text' => 'Yes, we do! Saltmarsh Travel specialises in tailor-made honeymoons to Japan, planned by a dedicated consultant. Would you like help starting your itinerary, or shall I have the team give you a call?'],
            ['who' => 'visitor', 'name' => 'Visitor', 'text' => 'We were thinking two weeks in April, Tokyo and Kyoto. What would you suggest?'],
            ['who' => 'bot', 'name' => 'Saltmarsh Travel', 'text' => 'Lovely choice! April is cherry blossom season, so it\'s magical but books up fast. For two weeks, a classic route is 5-6 nights in Tokyo, then the bullet train to Kyoto, with a day trip to Nara or Osaka, and maybe a stop in Hakone for a ryokan stay. Want me to have a specialist consultant reach out with a tailored draft itinerary?'],
            ['who' => 'visitor', 'name' => 'Visitor', 'text' => 'Are you ATOL protected?'],
            ['who' => 'bot', 'name' => 'Saltmarsh Travel', 'text' => 'Yes, we\'re fully ATOL protected, so your holiday is secure. Want me to have a specialist consultant start planning your Japan honeymoon?'],
        ],
        'lead' => [
            'Name'  => 'Emma',
            'Phone' => '07700 900412',
            'Page'  => 'saltmarsh.levelupgrowth.io',
            'Asked' => 'Japan honeymoon, two weeks in April',
        ],
        'crm' => 'A new lead, scored and waiting, before anyone opened the laptop.',
    ],

    // Basic and Advanced, captured as a matched pair from the same screen at the same moment.
    'modes' => [
        ['name' => 'Basic', 'shot' => '50-basic', 'items' => 7,
         'line' => 'What needs you, and nothing else. Sarah, what wants attention, results, your website, your customers.'],
        ['name' => 'Advanced', 'shot' => '51-advanced', 'items' => 22,
         'line' => 'Every engine on the rail: the strategy room, the queue, each specialist, and every setting behind them.'],
    ],

    // The three doors before the footer. `live` is the truth test: a door that is not live says so and sells nothing.
    'doors' => [
        [
            'name' => 'WordPress plugin',
            'icon' => 'globe',
            'live' => true,
            'href' => '/next/product/seo/',
            'line' => 'Keep your WordPress site. The connector plugin puts the audits, keywords, quick wins and the chatbot inside your own admin.',
        ],
        [
            'name' => 'Managed hosting',
            'icon' => 'server',
            'live' => false,
            'href' => '/next/product/hosting/',
            'line' => 'Hosting we run for you. Not sold yet, and nothing is provisioned today — tell us if you want it and you will hear first.',
        ],
        [
            'name' => 'Custom AI for larger teams',
            'icon' => 'building',
            'live' => true,
            'href' => '/next/contact/?topic=custom',
            'line' => 'More sites, more brands, or a workflow of your own. Tell us the shape of the problem and we will tell you honestly whether we fit.',
        ],
    ],
];
