<?php
declare(strict_types=1);
/**
 * GLASS-SITE-2 (2026-09-30): the live panels — self-playing glass mockups that replace screenshots on the product,
 * solution and agencies pages (Owner: "update images with animated mockups on pages that fits. enterprise quality just like
 * the homepage"). Each panel is complete at rest (no JavaScript, reduced motion: the finished state shows); with Motion,
 * assets/mk/live.js resets it and plays its sequence while it is on screen, then loops. Styles: assets/mk/live.css plus the
 * lug-glass.css components every page already carries.
 */

function live_panel_exists(string $key): bool
{
    return in_array($key, ['build', 'team', 'seo', 'write', 'social', 'crm', 'calendar', 'bot', 'creative', 'video', 'automation', 'aria', 'domains', 'email', 'hosting', 'cc', 'workspaces'], true);
}

/** Which panel illustrates a product page. */
function live_panel_for_product(string $slug): string
{
    $map = ['website-builder' => 'build', 'ai-workforce' => 'team', 'seo' => 'seo', 'content' => 'write', 'social' => 'social', 'crm' => 'crm',
        'calendar' => 'calendar', 'chatbot' => 'bot', 'creative' => 'creative', 'video' => 'video', 'automation' => 'automation', 'aria' => 'aria',
        'domains' => 'domains', 'business-email' => 'email', 'hosting' => 'hosting'];
    return $map[$slug] ?? '';
}

function live_panel(string $key, string $caption = ''): string
{
    if (! live_panel_exists($key)) { return ''; }
    $av = fn (string $slug) => '/img/agents/' . $slug . '.webp';
    $ic = fn (string $d) => '<svg class="ic ic--sm" viewBox="0 0 24 24"><path d="' . $d . '"/></svg>';
    $check = $ic('m5 12 5 5 9-10');
    $url = ['build' => 'blackdoor.levelupgrowth.io', 'team' => 'app.levelupgrowth.io/app', 'seo' => 'SEO · blackdoor.levelupgrowth.io', 'write' => 'Write · blackdoor.levelupgrowth.io', 'social' => 'Social · this week',
        'crm' => 'Clients', 'calendar' => 'Calendar · this week', 'bot' => 'saltmarsh.levelupgrowth.io', 'creative' => 'Studio', 'video' => 'Studio · video', 'automation' => 'Automation', 'aria' => 'Aria',
        'domains' => 'Domains', 'email' => 'hello@blackdoor.com', 'hosting' => 'Hosting · blackdoor.com', 'cc' => 'app.levelupgrowth.io/app', 'workspaces' => 'Agency · 2 workspaces'][$key];
    $h = '';
    switch ($key) {
        case 'build':
            $h = '<div class="lv-build"><div class="lg-glass lg-glass--thick lg-stack lv-chat"><div class="lg-row gap-2 lv-chat__head"><span class="lg-avatar lg-presence lv-av-logo"><img src="/img/logo-icon-40.png" alt="" width="20" height="20"></span><div class="lg-stack"><span class="t-subhead t-strong">Arthur</span><span class="t-caption c-3">AI website builder</span></div></div>'
               . '<div class="lg-stack gap-2 lv-chat__body"><div class="lg-bubble lv-b">Hi! Tell me about your business and I\'ll build your website today.</div><div class="lg-bubble lg-bubble--me lv-b" data-lv="ask">A neighbourhood restaurant in Norwich. Twelve dishes, seasonal menu, private hire.</div><div class="lg-typing lg-glass lg-glass--thin" data-lv="typing" hidden><i></i><i></i><i></i></div><div class="lg-bubble lv-b" data-lv="reply">On it. Black Door: candlelit, the menu and booking up front. Building now.</div><span class="lg-event lg-glass lg-glass--thin" data-lv="live">' . $check . '<span class="t-caption">Live at blackdoor.levelupgrowth.io</span></span></div>'
               . '<div class="lv-chat__composer"><div class="lg-composer__field lg-glass lg-glass--thick"><span class="lg-composer__input"><span data-lv="typed"></span><span class="lv-caret" data-lv="caret" hidden></span></span><span class="lg-btn lg-btn--primary lg-btn--icon lg-btn--sm" aria-hidden="true">' . $ic('M12 19V5M5 12l7-7 7 7') . '</span></div></div></div>'
               . '<div class="lv-site"><div class="lv-reveal"><img src="/next/assets/product/templates/restaurant.webp" alt="The restaurant website Arthur built" width="1440" height="900" data-lv="img" loading="lazy" decoding="async"><div class="lv-skel" data-lv="skel" hidden><i style="width:40%"></i><i style="height:72px"></i><i style="width:60%"></i></div></div><div class="lv-site__foot"><div class="lg-row lg-between"><span class="t-caption c-2" data-lv="stage">Published</span><span class="t-caption t-num c-3"><span data-lv="pct">100</span>%</span></div><div class="lg-meter"><i data-lv="meter"></i></div></div></div></div>';
            break;
        case 'team':
            $h = '<div class="lv-cols"><div class="lg-glass lg-card lg-stack lv-card" style="gap:0"><div class="lg-row lg-between lv-card__head"><span class="t-eyebrow">Your team right now</span><span class="t-caption c-3"><span data-lv="count">5</span> events</span></div>'
               . '<div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('elena') . '" alt=""><div class="lg-stack"><span class="t-subhead">Elena captured a new lead</span><span class="t-caption c-3">just now</span></div></div>'
               . '<div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('marcus') . '" alt=""><div class="lg-stack"><span class="t-subhead">Marcus scheduled Friday\'s post</span><span class="t-caption c-3">2 minutes ago</span></div></div>'
               . '<div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('priya') . '" alt=""><div class="lg-stack"><span class="t-subhead">Priya finished: Autumn menu article</span><span class="t-caption c-3">18 minutes ago</span></div></div>'
               . '<div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('james') . '" alt=""><div class="lg-stack"><span class="t-subhead">James audited 12 pages</span><span class="t-caption c-3">1 hour ago</span></div></div>'
               . '<div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('sarah') . '" alt=""><div class="lg-stack"><span class="t-subhead">Sarah queued: Private hire landing page</span><span class="t-caption c-3">2 hours ago</span></div></div></div>'
               . '<div class="lg-stack gap-3"><div class="lg-glass lg-card lg-stack gap-3 lv-card"><div class="lg-row lg-between"><span class="t-eyebrow">Needs your approval</span><span class="lg-count" data-lv="pending">2</span></div>'
               . '<div class="lg-glass lg-glass--thin lg-stack gap-2 lv-appr" data-lv="appr1"><div class="lg-row gap-2"><img class="lg-avatar lg-avatar--sm" src="' . $av('priya') . '" alt=""><div class="lg-stack"><span class="t-subhead t-strong">Private hire page · write</span><span class="t-caption c-3">Priya · 2 credits</span></div></div><div class="lg-row gap-2"><span class="lg-btn lg-btn--primary lg-btn--sm lg-grow">Approve</span><span class="lg-btn lg-btn--glass lg-btn--sm lg-grow">Not now</span></div></div>'
               . '<div class="lg-glass lg-glass--thin lg-stack gap-2 lv-appr" data-lv="appr2"><div class="lg-row gap-2"><img class="lg-avatar lg-avatar--sm" src="' . $av('marcus') . '" alt=""><div class="lg-stack"><span class="t-subhead t-strong">Friday\'s post · social</span><span class="t-caption c-3">Marcus · 4 credits</span></div></div><div class="lg-row gap-2"><span class="lg-btn lg-btn--primary lg-btn--sm lg-grow">Approve</span><span class="lg-btn lg-btn--glass lg-btn--sm lg-grow">Not now</span></div></div></div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card"><span class="t-eyebrow">On it now</span>'
               . '<div class="lg-row gap-2 lv-who"><img class="lg-avatar lg-avatar--sm" src="' . $av('sarah') . '" alt=""><span class="t-subhead t-strong">Sarah</span><span class="lv-status" data-lv-status="Planning October|Pricing a campaign|Briefing Priya"><i></i><span>Planning October</span></span></div>'
               . '<div class="lg-row gap-2 lv-who"><img class="lg-avatar lg-avatar--sm" src="' . $av('james') . '" alt=""><span class="t-subhead t-strong">James</span><span class="lv-status" data-lv-status="Auditing 12 pages|Tracking 8 keywords|Checking answer engines"><i></i><span>Auditing 12 pages</span></span></div>'
               . '<div class="lg-row gap-2 lv-who"><img class="lg-avatar lg-avatar--sm" src="' . $av('marcus') . '" alt=""><span class="t-subhead t-strong">Marcus</span><span class="lv-status" data-lv-status="Scheduling Friday 9:00|Drafting a carousel|Reading the week\'s results"><i></i><span>Scheduling Friday 9:00</span></span></div></div></div></div>';
            break;
        case 'seo':
            $kw = [['private hire norwich', 31, 4], ['restaurant norwich seasonal menu', 18, 3], ['best bistro norwich', 27, 7], ['norwich private dining', 42, 9]];
            $rows = '';
            foreach ($kw as $i => [$k, $from, $to]) { $rows .= '<div class="lv-kw" data-lv="kw" data-from="' . $from . '" data-to="' . $to . '"><span class="t-subhead lv-kw__q">' . e($k) . '</span><span class="lv-kw__pos t-num" data-lv="pos">#' . $to . '</span><span class="lv-kw__delta t-caption" data-lv="delta">▲ ' . ($from - $to) . '</span></div>'; }
            $h = '<div class="lv-cols lv-cols--seo"><div class="lg-glass lg-card lg-stack gap-2 lv-card" style="align-items:center;text-align:center"><span class="t-eyebrow">Site score</span><div class="lv-ring"><svg viewBox="0 0 120 120" width="120" height="120"><circle class="bg" cx="60" cy="60" r="52"></circle><circle class="fg" data-lv="ring" cx="60" cy="60" r="52" stroke-dasharray="327" stroke-dashoffset="39"></circle></svg><span class="lv-ring__n t-num"><b data-lv="score">88</b><small>/100</small></span></div><span class="t-caption c-2" data-lv="scoreline">21 checks passed · 3 to fix</span></div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card"><div class="lg-row lg-between"><span class="t-eyebrow">Tracked keywords</span><span class="t-caption c-3">Google · UK</span></div>' . $rows . '</div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card lv-span"><span class="t-eyebrow">Quick wins</span><div class="lv-checks"><span class="lv-check" data-lv="win">' . $check . 'Missing meta descriptions · 3 pages</span><span class="lv-check" data-lv="win">' . $check . 'Image alt text · 12 images</span><span class="lv-check" data-lv="win">' . $check . 'Private hire page · answer-engine markup</span><span class="lv-check" data-lv="win">' . $check . 'Google Business Profile · hours</span></div><span class="lg-event lg-glass lg-glass--thin" data-lv="handed">' . $check . '<span class="t-caption">Handed to James and Priya · waiting for your OK</span></span></div></div>';
            break;
        case 'write':
            $h = '<div class="lv-cols"><div class="lg-glass lg-card lg-stack gap-3 lv-card lv-span"><div class="lg-row lg-between"><span class="t-eyebrow">Article</span><span class="lg-badge lg-badge--success" data-lv="published">' . $check . 'Published</span></div><span class="t-title3 lv-title" data-lv="title">Cherry blossom season in Japan: when to go and what to book</span><div class="lv-lines" data-lv="lines"><i style="width:96%"></i><i style="width:88%"></i><i style="width:92%"></i><i style="width:64%"></i></div>'
               . '<div class="lg-row lg-between"><span class="t-caption c-3">Words</span><span class="t-subhead t-strong t-num" data-lv="words">1,016</span></div><div class="lg-meter"><i data-lv="meter"></i></div></div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card"><span class="t-eyebrow">Ready to publish</span><div class="lv-checks"><span class="lv-check" data-lv="chk">' . $check . 'Meta description</span><span class="lv-check" data-lv="chk">' . $check . 'Featured image with alt text</span><span class="lv-check" data-lv="chk">' . $check . 'Answer-engine markup</span><span class="lv-check" data-lv="chk">' . $check . 'Internal links · 4</span></div></div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card" style="align-items:center;text-align:center"><span class="t-eyebrow">Answer engines</span><div class="lv-ring lv-ring--sm"><svg viewBox="0 0 120 120" width="96" height="96"><circle class="bg" cx="60" cy="60" r="52"></circle><circle class="fg" data-lv="ring" cx="60" cy="60" r="52" stroke-dasharray="327" stroke-dashoffset="33"></circle></svg><span class="lv-ring__n t-num"><b data-lv="score">90</b><small>/100</small></span></div><span class="t-caption c-2">Priya · 2 credits</span></div></div>';
            break;
        case 'social':
            $days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
            $posts = [1 => ['Behind the pass', 'ig'], 3 => ['Seasonal menu · 12 dishes', 'fb'], 5 => ['Private hire nights', 'ig'], 6 => ['Sunday roast', 'fb']];
            $grid = '';
            foreach ($days as $i => $d) { $grid .= '<div class="lv-day' . (isset($posts[$i]) ? ' has' : '') . '"><span class="lv-day__n">' . $d . '</span>' . (isset($posts[$i]) ? '<span class="lv-post lv-post--' . $posts[$i][1] . '" data-lv="post"><i></i>' . e($posts[$i][0]) . '</span>' : '') . '</div>'; }
            $h = '<div class="lg-stack gap-3"><div class="lg-glass lg-card lg-stack gap-2 lv-card"><div class="lg-row lg-between"><span class="t-eyebrow">This week</span><span class="lg-badge lg-badge--info" data-lv="badge">4 posts · waiting for your OK</span></div><div class="lv-week">' . $grid . '</div></div>'
               . '<div class="lv-cols"><div class="lg-glass lg-card lg-stack gap-2 lv-card"><div class="lg-row gap-2"><img class="lg-avatar lg-avatar--sm" src="' . $av('marcus') . '" alt=""><div class="lg-stack"><span class="t-subhead t-strong">Marcus</span><span class="t-caption c-3">Social media manager</span></div></div><div class="lv-lines"><i style="width:90%"></i><i style="width:70%"></i></div><p class="t-subhead lv-caption" data-lv="caption">Friday is private hire night. Twelve seats, one long table, the menu we cook for you. Book the room.</p><div class="lg-row gap-2"><span class="lg-badge lg-badge--brand">Fri 09:00</span><span class="lg-badge">Instagram · Facebook</span></div></div>'
               . '<div class="lg-glass lg-card lg-stack gap-2 lv-card"><span class="t-eyebrow">Last week</span><div class="lv-stat"><b class="t-num" data-lv="reach" data-n="4820">4,820</b><span class="t-caption c-2">reach</span></div><div class="lv-stat"><b class="t-num" data-lv="clicks" data-n="212">212</b><span class="t-caption c-2">clicks to the booking page</span></div><div class="lv-stat"><b class="t-num" data-lv="bookings" data-n="9">9</b><span class="t-caption c-2">bookings</span></div></div></div></div>';
            break;
        case 'crm':
            $card = fn (string $name, string $line, string $who, string $key) => '<div class="lg-glass lg-glass--thin lg-stack lv-lead" data-lv="' . $key . '"><span class="t-subhead t-strong">' . $name . '</span><span class="t-caption c-2">' . $line . '</span><span class="t-caption c-3">' . $who . '</span></div>';
            $h = '<div class="lv-board"><div class="lv-col"><div class="lg-row lg-between lv-col__head"><span class="t-eyebrow">New</span><span class="lg-count" data-lv="n1">1</span></div>' . $card('Emma · 07700 900412', 'Private hire, 12 people, 14 Oct', 'from the chatbot · 11:04 pm', 'lead-new') . $card('Tom Harker', 'Table for 6, Saturday', 'from the booking form', 'lead-a') . '</div>'
               . '<div class="lv-col"><div class="lg-row lg-between lv-col__head"><span class="t-eyebrow">Replied</span><span class="lg-count" data-lv="n2">2</span></div>' . $card('Emma · 07700 900412', 'Sarah replied in 2 minutes', 'menu and prices sent', 'lead-mid') . $card('Priya Raman', 'Birthday dinner for 8', 'call booked for Tuesday', 'lead-b') . '</div>'
               . '<div class="lv-col"><div class="lg-row lg-between lv-col__head"><span class="t-eyebrow">Booked</span><span class="lg-count" data-lv="n3">3</span></div>' . $card('Emma · 07700 900412', 'Private hire · 14 Oct · deposit paid', 'in the Calendar', 'lead-done') . $card('The Rowe family', 'Sunday roast · 4', 'reminder sent', 'lead-c') . $card('Marta Silva', 'Tasting menu · 2', 'reminder sent', 'lead-d') . '</div></div>';
            break;
        case 'calendar':
            $h = '<div class="lg-stack gap-3"><div class="lg-glass lg-card lv-card lg-stack gap-2"><div class="lg-row lg-between"><span class="t-eyebrow">This week</span><span class="lg-badge lg-badge--info" data-lv="badge">3 bookings · 1 call</span></div><div class="lv-cal">'
               . '<div class="lv-cal__day"><span class="lv-day__n">Mon</span><span class="lv-slot lv-slot--soft" data-lv="ev">09:30 · Strategy meeting with Sarah</span></div>'
               . '<div class="lv-cal__day"><span class="lv-day__n">Tue</span><span class="lv-slot" data-lv="ev">10:00 · Emma · private hire walkthrough</span></div>'
               . '<div class="lv-cal__day"><span class="lv-day__n">Wed</span></div>'
               . '<div class="lv-cal__day"><span class="lv-day__n">Thu</span><span class="lv-slot" data-lv="ev">18:30 · Tasting menu · Marta Silva · 2</span></div>'
               . '<div class="lv-cal__day"><span class="lv-day__n">Fri</span><span class="lv-slot" data-lv="ev">12:00 · Call · Priya Raman</span></div>'
               . '</div></div><div class="lg-toast lg-glass lg-glass--thick lv-toast" data-lv="toast"><span class="lg-toast__icon">' . $check . '</span><span class="t-subhead t-strong">Reminders sent · SMS and email, 24 h before</span></div></div>';
            break;
        case 'bot':
            $h = '<div class="lv-cols lv-cols--bot"><div class="lg-glass lg-glass--thick lg-stack lv-widget"><div class="lg-row lg-between lv-widget__head"><span class="t-subhead t-strong">Chat with us</span><span class="t-caption">Saltmarsh Travel</span></div><div class="lg-stack gap-2 lv-widget__body"><div class="lg-bubble lv-b">Hi! Tell me where you fancy going and I\'ll help you plan it.</div><div class="lg-bubble lg-bubble--me lv-b" data-lv="m">Looking for a honeymoon in Japan. Any ideas?</div><div class="lg-typing lg-glass lg-glass--thin" data-lv="typing" hidden><i></i><i></i><i></i></div><div class="lg-bubble lv-b" data-lv="m">Lovely choice. Our Tokyo to Kyoto honeymoon is built around ryokans and cherry blossom. Shall a consultant send you a quote? A name and number is all I need.</div><div class="lg-bubble lg-bubble--me lv-b" data-lv="m">Yes please. Emma, 07700 900412.</div><div class="lg-bubble lv-b" data-lv="m">Thanks Emma. Aiko will call you tomorrow morning.</div></div><div class="lv-chat__composer"><div class="lg-composer__field lg-glass lg-glass--thick"><span class="lg-composer__input"><span data-lv="typed"></span><span class="lv-caret" data-lv="caret" hidden></span></span></div></div></div>'
               . '<div class="lg-glass lg-glass--thick lg-stack gap-2 lv-card lv-leadcard"><div class="lg-row lg-between"><span class="t-eyebrow">Clients</span><span class="t-caption c-3">11:04 pm</span></div><div class="lg-row gap-3" data-lv="lead"><span class="lg-avatar lv-av-letter">E</span><div class="lg-stack lg-grow"><span class="t-subhead t-strong">Emma · 07700 900412</span><span class="t-caption c-2">Japan honeymoon, two weeks in April</span></div><span class="lg-badge lg-badge--success">New lead</span></div><span class="t-caption c-3" data-lv="nolead" hidden>Listening on saltmarsh.levelupgrowth.io…</span></div></div>';
            break;
        case 'creative':
            $tiles = [['Menu banner', 'lv-art--a'], ['Instagram square', 'lv-art--b'], ['Private hire hero', 'lv-art--c'], ['Story · 9:16', 'lv-art--d']];
            $t = '';
            foreach ($tiles as [$n, $c]) { $t .= '<figure class="lv-tile" data-lv="tile"><div class="lv-art ' . $c . '"><span class="lv-art__shimmer" data-lv="shimmer"></span></div><figcaption class="t-caption c-2">' . $n . '</figcaption></figure>'; }
            $h = '<div class="lg-stack gap-3"><div class="lg-glass lg-card lv-card lg-stack gap-2"><div class="lg-row lg-between"><span class="t-eyebrow">Brief</span><span class="lg-badge lg-badge--info" data-lv="state">4 ready · pick one</span></div><p class="t-subhead lv-brief" data-lv="brief">Candlelit long table, twelve seats, autumn menu, warm and quiet. Our colours.</p><div class="lg-meter"><i data-lv="meter"></i></div></div><div class="lv-tiles">' . $t . '</div></div>';
            break;
        case 'video':
            $scenes = [['Open on the pass', 'lv-art--c'], ['The long table', 'lv-art--a'], ['Twelve dishes', 'lv-art--d'], ['Book the room', 'lv-art--b']];
            $t = '';
            foreach ($scenes as $i => [$n, $c]) { $t .= '<figure class="lv-tile lv-tile--scene" data-lv="scene"><div class="lv-art ' . $c . '"><span class="lv-art__shimmer" data-lv="shimmer"></span><span class="lv-scene__n t-num">' . ($i + 1) . '</span></div><figcaption class="t-caption c-2" data-lv="cap">' . $n . '</figcaption></figure>'; }
            $h = '<div class="lg-stack gap-3"><div class="lv-tiles lv-tiles--scenes">' . $t . '</div><div class="lg-glass lg-card lv-card lg-stack gap-2"><div class="lg-row lg-between"><span class="t-subhead t-strong" data-lv="stage">Ready · 14 s · 9:16 and 16:9</span><span class="t-caption t-num c-3"><span data-lv="pct">100</span>%</span></div><div class="lg-meter"><i data-lv="meter"></i></div><span class="t-caption c-2">Voice-over, captions and your logo at the end · waiting for your OK</span></div></div>';
            break;
        case 'automation':
            $h = '<div class="lv-flow"><div class="lv-node lg-glass lg-card" data-lv="node"><span class="t-eyebrow">When</span><span class="t-subhead t-strong">A new lead arrives</span><span class="t-caption c-3">chatbot, form or call</span></div><span class="lv-link" data-lv="link"><i></i></span><div class="lv-node lg-glass lg-card" data-lv="node"><span class="t-eyebrow">Then</span><span class="t-subhead t-strong">Sarah replies in 2 minutes</span><span class="t-caption c-3">with your menu and prices</span></div><span class="lv-link" data-lv="link"><i></i></span><div class="lv-node lg-glass lg-card" data-lv="node"><span class="t-eyebrow">And</span><span class="t-subhead t-strong">Add to Clients</span><span class="t-caption c-3">stage: Replied</span></div><span class="lv-link" data-lv="link"><i></i></span><div class="lv-node lg-glass lg-card" data-lv="node"><span class="t-eyebrow">Unless booked</span><span class="t-subhead t-strong">Remind me Friday</span><span class="t-caption c-3">in the Calendar, with the thread</span></div></div><div class="lg-toast lg-glass lg-glass--thick lv-toast" data-lv="toast"><span class="lg-toast__icon">' . $check . '</span><span class="t-subhead t-strong">Ran 14 times this week · 9 booked</span></div>';
            break;
        case 'aria':
            $h = '<div class="lg-glass lg-glass--thick lg-stack lv-chat lv-chat--wide"><div class="lg-row gap-2 lv-chat__head"><img class="lg-avatar lg-presence" src="' . $av('aria') . '" alt="" width="36" height="36"><div class="lg-stack"><span class="t-subhead t-strong">Aria</span><span class="t-caption c-3">Knows the platform</span></div></div><div class="lg-stack gap-2 lv-chat__body"><div class="lg-bubble lg-bubble--me lv-b" data-lv="m">How do I connect the domain I already own?</div><div class="lg-typing lg-glass lg-glass--thin" data-lv="typing" hidden><i></i><i></i><i></i></div><div class="lg-bubble lv-b" data-lv="m">Three steps, about ten minutes:<br>1. Websites → your site → <b>Connect a domain</b>.<br>2. Add the two records we show you at your registrar.<br>3. We check every minute and switch SSL on when they resolve.<br>Want me to open that screen for you?</div><div class="lg-bubble lg-bubble--me lv-b" data-lv="m">Yes please.</div><div class="lg-bubble lv-b" data-lv="m">Done, it\'s open on your left. I\'ll tell you when the records resolve.</div></div><div class="lv-chat__composer"><div class="lg-composer__field lg-glass lg-glass--thick"><span class="lg-composer__input"><span data-lv="typed"></span><span class="lv-caret" data-lv="caret" hidden></span></span></div></div></div>';
            break;
        case 'domains':
            $h = '<div class="lg-stack gap-3"><div class="lg-glass lg-glass--thick lv-search"><span class="lv-search__q"><span data-lv="typed">blackdoor.com</span><span class="lv-caret" data-lv="caret" hidden></span></span><span class="lg-btn lg-btn--primary lg-btn--sm">Search</span></div><div class="lg-glass lg-card lv-card lg-stack gap-1"><div class="lv-dom" data-lv="dom"><span class="t-subhead t-strong">blackdoor.com</span><span class="lg-badge lg-badge--success">Available</span></div><div class="lv-dom" data-lv="dom"><span class="t-subhead t-strong">blackdoor.co.uk</span><span class="lg-badge lg-badge--success">Available</span></div><div class="lv-dom" data-lv="dom"><span class="t-subhead t-strong">blackdoor.restaurant</span><span class="lg-badge lg-badge--success">Available</span></div><div class="lv-dom" data-lv="dom"><span class="t-subhead t-strong">blackdoor.uk</span><span class="lg-badge">Taken</span></div></div>'
               . '<div class="lg-glass lg-card lv-card lg-stack gap-2"><span class="t-eyebrow">blackdoor.com</span><div class="lv-checks lv-checks--row"><span class="lv-check" data-lv="step">' . $check . 'Registered to you</span><span class="lv-check" data-lv="step">' . $check . 'Connected to your site</span><span class="lv-check" data-lv="step">' . $check . 'SSL on</span><span class="lv-check" data-lv="step">' . $check . 'Auto-renew on</span></div></div></div>';
            break;
        case 'email':
            $h = '<div class="lg-glass lg-glass--thick lg-stack lv-mail"><div class="lg-row lg-between lv-mail__head"><span class="t-subhead t-strong">hello@blackdoor.com</span><span class="lg-badge lg-badge--success">' . $check . 'Your domain</span></div>'
               . '<div class="lv-mailrow" data-lv="mail"><span class="lg-avatar lv-av-letter">E</span><div class="lg-stack lg-grow"><span class="t-subhead t-strong">Emma Clarke · Private hire on 14 Oct?</span><span class="t-caption c-2">Hi, we\'d love the long table for twelve…</span></div><span class="t-caption c-3">11:04 pm</span></div>'
               . '<div class="lv-mailrow" data-lv="mail"><span class="lg-avatar lv-av-letter" style="background:var(--tint);color:var(--accent-text)">S</span><div class="lg-stack lg-grow"><span class="t-subhead t-strong">Sarah · Re: Private hire on 14 Oct?</span><span class="t-caption c-2">Menu and prices attached, the room is yours if…</span></div><span class="t-caption c-3">11:06 pm</span></div>'
               . '<div class="lv-mailrow" data-lv="mail"><span class="lg-avatar lv-av-letter">T</span><div class="lg-stack lg-grow"><span class="t-subhead t-strong">Tom Harker · Table for 6 on Saturday</span><span class="t-caption c-2">Is 7:30 possible? We have a birthday…</span></div><span class="t-caption c-3">9:12 pm</span></div>'
               . '<div class="lv-mailrow" data-lv="mail"><span class="lg-avatar lv-av-letter">R</span><div class="lg-stack lg-grow"><span class="t-subhead t-strong">Riverside Farm · Invoice 2214</span><span class="t-caption c-2">This week\'s veg box, paid by card…</span></div><span class="t-caption c-3">4:40 pm</span></div>'
               . '<div class="lg-row lg-between lv-mail__foot"><span class="t-caption c-3">On your phone and your laptop, spam filtered</span><span class="t-caption c-3" data-lv="count">4 new</span></div></div>';
            break;
        case 'hosting':
            $h = '<div class="lv-cols lv-cols--host"><div class="lg-glass lg-card lv-card lg-stack gap-1"><span class="t-eyebrow">Uptime · 30 days</span><b class="lv-big t-num" data-lv="up">99.99%</b><div class="lg-meter"><i data-lv="meter" data-to="100"></i></div></div><div class="lg-glass lg-card lv-card lg-stack gap-1"><span class="t-eyebrow">Response</span><b class="lv-big t-num"><span data-lv="ms">118</span> ms</b><div class="lg-meter"><i data-lv="meter" data-to="88"></i></div></div><div class="lg-glass lg-card lv-card lg-stack gap-1"><span class="t-eyebrow">SSL</span><b class="lv-big">On</b><span class="t-caption c-2" data-lv="ssl">Renewed 3 days ago · next in 87 days</span></div><div class="lg-glass lg-card lv-card lg-stack gap-1"><span class="t-eyebrow">Backups</span><b class="lv-big">Daily</b><span class="t-caption c-2" data-lv="bk">Last one 2 h ago · restore in one click</span></div><div class="lg-glass lg-card lv-card lg-stack gap-2 lv-span"><span class="t-eyebrow">Traffic today</span><div class="lv-bars">' . implode('', array_map(fn ($v) => '<i data-lv="bar" style="height:' . $v . '%"></i>', [22, 30, 26, 41, 58, 47, 66, 74, 61, 83, 90, 72, 54, 60])) . '</div><span class="t-caption c-2">Cached at the edge, served from the nearest city</span></div></div>';
            break;
        case 'cc':
            $h = '<div class="lv-app"><aside class="lv-side"><div class="lg-row gap-2 lv-side__brand"><img src="/img/logo-icon-40.png" alt="" width="20" height="20"><span class="t-subhead t-strong">LevelUpGrowth</span></div><div class="lv-nav"><img class="lg-avatar" src="' . $av('sarah') . '" alt="" width="20" height="20">Sarah</div><span class="t-eyebrow lv-side__h">Workspace</span><div class="lv-nav is-on">Command Center</div><div class="lv-nav">Strategy Room</div><div class="lv-nav">Campaigns</div><div class="lv-nav">Review Queue<span class="lg-count" data-lv="pending">2</span></div><span class="t-eyebrow lv-side__h">Engines</span><div class="lv-nav">Clients</div><div class="lv-nav">SEO</div><div class="lv-nav">Write</div><div class="lv-nav">Social</div></aside>'
               . '<div class="lv-main"><div class="lg-row lg-between"><div class="lg-stack"><span class="t-title3">Good morning, Owner.</span><span class="t-caption c-3">7 agents on this workspace</span></div><span class="lg-badge lg-badge--success"><span class="lg-dot"></span>LIVE</span></div><div class="lv-stats"><div class="lg-glass lg-card lg-stat lv-stat-card"><span class="t-eyebrow">Tasks done</span><span class="lg-stat__value" data-lv="count" data-n="51">51</span></div><div class="lg-glass lg-card lg-stat lv-stat-card"><span class="t-eyebrow">Published</span><span class="lg-stat__value" data-lv="count" data-n="12">12</span></div><div class="lg-glass lg-card lg-stat lv-stat-card"><span class="t-eyebrow">Leads</span><span class="lg-stat__value" data-lv="count" data-n="34">34</span></div><div class="lg-glass lg-card lg-stat lv-stat-card"><span class="t-eyebrow">Keywords</span><span class="lg-stat__value" data-lv="count" data-n="8">8</span></div></div>'
               . '<div class="lg-glass lg-card lg-stack lv-card" style="gap:0"><div class="lg-row lg-between lv-card__head"><span class="t-eyebrow">Your team right now</span></div><div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('elena') . '" alt=""><div class="lg-stack"><span class="t-subhead">Elena captured a new lead</span><span class="t-caption c-3">just now</span></div></div><div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('marcus') . '" alt=""><div class="lg-stack"><span class="t-subhead">Marcus scheduled Friday\'s post</span><span class="t-caption c-3">2 minutes ago</span></div></div><div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av('priya') . '" alt=""><div class="lg-stack"><span class="t-subhead">Priya finished: Autumn menu article</span><span class="t-caption c-3">18 minutes ago</span></div></div></div></div></div>';
            break;
        case 'workspaces':
            $ws = fn (string $name, string $site, string $credits, string $ev1, string $ev2, string $a1, string $a2) => '<div class="lg-glass lg-card lv-card lg-stack gap-2" data-lv="ws"><div class="lg-row lg-between"><span class="t-subhead t-strong">' . $name . '</span><span class="lg-badge lg-badge--success"><span class="lg-dot"></span>Live</span></div><span class="t-caption c-2">' . $site . '</span><div class="lg-meter"><i data-lv="meter" data-to="' . $credits . '"></i></div><span class="t-caption c-3">' . $credits . '% of this month\'s credits used</span><div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av($a1) . '" alt=""><span class="t-subhead">' . $ev1 . '</span></div><div class="lg-row-item lv-evt"><img class="lg-avatar lg-avatar--sm" src="' . $av($a2) . '" alt=""><span class="t-subhead">' . $ev2 . '</span></div></div>';
            $h = '<div class="lg-stack gap-3"><div class="lg-row lg-between"><span class="t-eyebrow">Your clients</span><span class="lg-badge lg-badge--brand">White-label · your name on it</span></div><div class="lv-cols">' . $ws('Black Door · restaurant', 'blackdoor.com · 3 sites', '62', 'Priya published the autumn menu', 'Elena logged 4 enquiries', 'priya', 'elena') . $ws('Forge Athletic · gym', 'forgeathletic.co.uk · 1 site', '38', 'Marcus scheduled the week', 'James fixed 6 quick wins', 'marcus', 'james') . '</div><div class="lg-toast lg-glass lg-glass--thick lv-toast" data-lv="toast"><span class="lg-toast__icon">' . $check . '</span><span class="t-subhead t-strong">Two workspaces, one login, one invoice to each client</span></div></div>';
            break;
    }
    return '<figure class="lv lg-glass lg-glass--thick" data-live="' . e($key) . '"><div class="lv-bar"><i></i><i></i><i></i><span class="lv-url">' . e($url) . '</span></div><div class="lv-body">' . $h . '</div>'
         . ($caption !== '' ? '<figcaption class="lv-cap">' . e($caption) . '</figcaption>' : '') . '</figure>';
}
