<?php
declare(strict_types=1);
/**
 * The twelve launched products and the three held infrastructure products. Every capability maps to a certified
 * engine (certification records 6–7 September 2026). Plan availability is NOT written here: it is derived from the
 * plan feature flags at build time ('flag' below names the flag; 'counter' names a per-plan number to show).
 */
return [
    'launched' => [
        ['slug' => 'website-builder', 'icon' => 'globe', 'name' => 'Website builder', 'engine' => 'Builder, Arthur', 'flag' => 'website_builder',
            'promise' => 'A site built for your industry, edited in place, hosted, and yours to export.',
            'lede' => 'Tell Arthur about the business. The site comes back built for your industry, with your copy, your images and your details, on a LevelUp subdomain with SSL, ready to publish. Edit any element in place. Export the files whenever you like.',
            'capabilities' => [['Built from your brief', 'Industry copy, sections, colours and images set from what you tell us, not from lorem ipsum.'], ['Edited in place', 'Click any heading, paragraph, image or button on the live page and change it. Arthur can recolour, restyle and add sections on request.'], ['Hosted and exportable', 'Published on your subdomain with SSL the moment you approve it. Export the static files at any time.']],
            'limit' => 'Arthur builds one site per website; custom code beyond what Arthur builds is not a service we sell.',
            'faq' => [['Can I use my own domain?', 'Your site publishes on a LevelUp subdomain with SSL. Connecting a domain you already own is part of the infrastructure products, listed separately on this site.'], ['Can I edit the site myself?', 'Yes. Every text, image and button is editable in place, and Arthur makes larger changes on request, always for your approval.'], ['What happens if I leave?', 'You export the site as files and take it with you.']]],
        ['slug' => 'ai-workforce', 'icon' => 'users', 'name' => 'AI workforce', 'engine' => 'Sarah and the specialist agents', 'flag' => 'ai_agents',
            'promise' => '{specialists} named specialists, one manager, your approval.',
            'lede' => 'Sarah, the Digital Marketing Manager, turns your goals into a plan and delegates to specialists across SEO, content, social and customers. Every finished task passes her review for alignment, metadata and provenance before you see it. You approve; then it goes live.',
            'capabilities' => [['Plans, not prompts', 'Sarah proposes the next piece of work from your brief and your data, and asks before spending credits on it.'], ['A review before you see it', 'Work that fails the review on topic, metadata or source is sent back to draft. It is never counted as done and never bulk-published.'], ['Specialists you choose', 'Plans include Sarah plus a number of specialists; add more for a flat monthly price.']],
            'limit' => 'The workforce works inside your account: your site, your CRM, your content. It does not log in to third-party tools on your behalf.',
            'faq' => [['Does anything publish without me?', 'No. Every publish, send or post waits for your approval, and Sarah\'s review runs before that.'], ['How are credits used?', 'Each task costs credits for the research, writing, images or video it involves. Sarah tells you the cost before running work that spends them.'], ['Can I talk to the specialists?', 'You talk to Sarah, who briefs and manages the specialists, and to Aria for anything about how the platform works.']]],
        ['slug' => 'seo', 'icon' => 'search', 'name' => 'SEO', 'engine' => 'SEO suite', 'flag' => 'seo_suite', 'counter' => ['max_tracked_keywords', 'tracked keywords'],
            'promise' => 'Know what holds your site back, track what matters, fix it.',
            'lede' => 'The SEO suite audits your site, tracks the keywords you care about, and hands the fixes to the workforce: technical issues to Alex, local signals to Diana, links to Ryan, content briefs to Priya.',
            'capabilities' => [['Technical audit', 'Crawl issues, metadata gaps, speed and structure, with fixes proposed on your own site.'], ['Keyword tracking', 'A tracked list per plan, with movement over time and the content that should target each term.'], ['Briefs to content', 'Every keyword worth writing for becomes a brief the content team can pick up.']],
            'limit' => 'Rankings depend on your market and your competitors; we show movement and never promise positions.',
            'faq' => [['Do you guarantee rankings?', 'No, and nobody honest does. We show what changed and why.'], ['Does it work on sites you did not build?', 'The suite audits any site you connect; fixes are applied automatically only on sites built here.'], ['How many keywords can I track?', 'It depends on the plan; the number is on the pricing page and read from the same table the platform enforces.']]],
        ['slug' => 'content', 'icon' => 'pen', 'name' => 'Content', 'engine' => 'Write engine', 'flag' => 'content_writing',
            'promise' => 'Articles briefed from your keywords, written with their metadata, checked before they count.',
            'lede' => 'Priya and the content team write from briefs the SEO suite produces. Every article carries its title tag, description, focus keyword and structured data, and passes Sarah\'s review before it reaches you for approval.',
            'capabilities' => [['Briefed, not improvised', 'Each piece starts from a keyword brief and your brand notes, so the topic is yours before a word is written.'], ['Complete on arrival', 'Metadata, image alt text, categories and schema are part of the article, not an afterthought.'], ['On your site, in your voice', 'Published to your blog on approval, in the tone you set once.']],
            'limit' => 'Content is drafted by the workforce and approved by you; we do not offer human editorial review as a service.',
            'faq' => [['Will it write off-topic?', 'The review gate rejects work that drifts from your brief. Rejected drafts never publish.'], ['Can I edit before publishing?', 'Yes, every draft is editable before approval.'], ['Is the content disclosed as AI-written?', 'On our own blog, yes, with a byline. On yours, that is your decision.']]],
        ['slug' => 'social', 'icon' => 'share', 'name' => 'Social', 'engine' => 'Social engine', 'flag' => 'social',
            'promise' => 'A month of posts planned, drafted and scheduled for your approval.',
            'lede' => 'Marcus plans the calendar, Maya, Zara, Tyler and Zoe write for the channel, and every post waits in the queue for your approval. Publishing goes through the channel connections you authorise.',
            'capabilities' => [['Planned as a calendar', 'Thirty days at a time, balanced across the channels you use, tied to what the site and blog are doing.'], ['Written per channel', 'Formats, lengths and hooks differ by network; so do the writers.'], ['Approved, then scheduled', 'Nothing posts until you approve it; the queue shows exactly what is waiting.']],
            'limit' => 'Publishing requires you to connect each channel and authorise the connection; until a channel is connected, posts are prepared and scheduled but not sent.',
            'faq' => [['Which channels?', 'The engine plans for the networks you connect. Connection is per channel and per workspace.'], ['Can it post automatically?', 'Only what you approved, on the schedule you approved.'], ['Do I get images?', 'Yes, the creative engine supplies images in each channel\'s sizes.']]],
        ['slug' => 'crm', 'icon' => 'building', 'name' => 'CRM', 'engine' => 'CRM', 'flag' => 'crm',
            'promise' => 'Every lead from your site, chatbot and forms in one pipeline you own.',
            'lede' => 'Leads arrive from your site\'s forms, the chatbot and booking requests, land in one pipeline with their source and notes, and are followed up by rules you set. Export at any time.',
            'capabilities' => [['Capture everywhere', 'Contact forms, booking requests and chatbot conversations all create or update the same lead.'], ['Pipeline and follow-up', 'Stages, notes, tags and automated follow-ups, with the whole history on the record.'], ['Yours to export', 'One click exports your contacts and leads.']],
            'limit' => 'The CRM is built for owner-operated businesses and agencies managing client workspaces, not for enterprise sales teams with hundreds of seats.',
            'faq' => [['Can my team use it?', 'Team seats are set by plan and shown on the pricing page.'], ['Does it send email to my leads?', 'The CRM sends the notifications and confirmations your forms and bookings need. Bulk email marketing is not part of the product.'], ['Can I import existing contacts?', 'Yes, by CSV.']]],
        ['slug' => 'calendar', 'icon' => 'calendar', 'name' => 'Calendar', 'engine' => 'Calendar and booking', 'flag' => 'calendar',
            'promise' => 'Online booking from your site, with reminders and automations.',
            'lede' => 'Customers book from your site or a shareable link. Bookings land on your calendar and in the CRM, reminders go out, and the rules you set handle the follow-up.',
            'capabilities' => [['Booking page on your site', 'A booking section on the site itself and a link you can share anywhere.'], ['Reminders and confirmations', 'Sent automatically through the account mail pipeline and recorded.'], ['Connected to the CRM', 'Every booking is a lead with a history.']],
            'limit' => 'The calendar handles bookings and availability; it is not a replacement for your personal calendar application.',
            'faq' => [['Can I take payments at booking?', 'Booking captures the appointment; payment collection is not part of the calendar product.'], ['Can customers cancel?', 'Yes, from the confirmation they receive.'], ['Multiple staff?', 'Availability is set per workspace; team seats follow the plan.']]],
        ['slug' => 'chatbot', 'icon' => 'bot', 'name' => 'Chatbot', 'engine' => 'Website chatbot', 'flag' => 'chatbot_included', 'counter' => ['chatbot_messages_per_month', 'messages a month'],
            'promise' => 'Trained on your business, answering on your site, capturing leads into the CRM.',
            'lede' => 'The chatbot answers from the knowledge you give it, only on the domains you allow, and hands the conversation to you when it should. Names, phone numbers and booking requests go straight into the CRM.',
            'capabilities' => [['Knows your business', 'Upload documents and pages; the number of knowledge documents follows the plan.'], ['Stays in scope', 'Answers what it knows, says so when it does not, and never invents a price or a promise.'], ['Captures leads', 'Contact details and booking requests become CRM leads with the conversation attached.']],
            'limit' => 'The chatbot runs on sites you connect and within the monthly message allowance of your plan.',
            'faq' => [['Can it be embedded on a site not built here?', 'Yes, on domains you allow for your workspace.'], ['What does a message cost?', 'One credit per exchange, within the plan\'s monthly allowance.'], ['Can it book appointments?', 'It captures booking requests into the CRM and calendar for confirmation.']]],
        ['slug' => 'creative', 'icon' => 'image', 'name' => 'Creative', 'engine' => 'Creative and image engine', 'flag' => 'image_generation',
            'promise' => 'Images and ad creatives in every size your channels need.',
            'lede' => 'Brand-consistent images for the site, the blog and social, produced in the sizes each channel requires, with your subject kept in the frame.',
            'capabilities' => [['On brief', 'Images follow your brand notes and the subject you ask for.'], ['Every size', 'Square, story, banner and hero formats from one request.'], ['Into the site and posts', 'Delivered where they are used: the builder, the blog and the social queue.']],
            'limit' => 'Generated images are illustrations of your business, not photographs of it; use your own photos where authenticity matters.',
            'faq' => [['Can I use my own images?', 'Yes, upload and crop them in the builder.'], ['Are the images mine?', 'Yes, they are generated for your account and stored in your media library.'], ['Do they cost credits?', 'Yes, per image, within your plan\'s allowance.']]],
        ['slug' => 'video', 'icon' => 'video', 'name' => 'Video', 'engine' => 'Studio', 'flag' => 'video_generation',
            'promise' => 'Short-form and promotional video produced in the Studio.',
            'lede' => 'Chris writes the script, the Studio assembles the video from your brand, your images and generated scenes, and you review it in the editor before it goes anywhere.',
            'capabilities' => [['Scripted first', 'A script for your approval before any rendering spends credits.'], ['Assembled from your brand', 'Your colours, your images and generated scenes, in the formats your channels use.'], ['Reviewed before use', 'A full preview in the Studio editor before you approve.']],
            'limit' => 'The Studio editor is a desktop experience; review and edit on a computer, not a phone.',
            'faq' => [['How long are the videos?', 'Short-form and promotional lengths suited to social channels and the site.'], ['What if a render fails?', 'Credits for a failed render are returned automatically.'], ['Can I add my own footage?', 'Yes, upload it to the media library and use it in the Studio.']]],
        ['slug' => 'automation', 'icon' => 'zap', 'name' => 'Automation', 'engine' => 'Automation rules', 'flag' => 'automation',
            'promise' => 'The rules that run themselves: follow-ups, reminders, hand-offs.',
            'lede' => 'Automation is the plain rules of running a business: when a lead arrives, when a booking is made, when a form is submitted. You set the rule once; it runs every time.',
            'capabilities' => [['Triggers from your data', 'Leads, bookings, forms and chatbot conversations start rules.'], ['Actions you can see', 'Notifications, tags, stage changes, reminders, all recorded on the lead.'], ['Never marketing email', 'Automation sends the account and booking mail your business needs, not bulk campaigns.']],
            'limit' => 'Automation acts inside your account; it does not connect to external tools or send bulk email.',
            'faq' => [['Is this the same as the AI workforce?', 'No. Automation is deterministic rules; the workforce reasons and proposes.'], ['Can I turn a rule off?', 'Any time, from the rule itself.'], ['Does it use credits?', 'No. Rules are included in the plan.']]],
        ['slug' => 'aria', 'icon' => 'message', 'name' => 'Aria', 'engine' => 'Platform assistant', 'flag' => 'ai_assistant',
            // DEC-0054 (2026-09-15): Aria is the platform FAQ - documentation answers on every plan, metered like every chat.
            'promise' => 'The FAQ of the whole platform, in your sidebar.',
            'description' => 'The FAQ of the whole platform, in your sidebar. Aria answers questions about how LevelUpGrowth works: what a feature does, where it lives in the app, what each plan includes, what things cost in credits.',
            'lede' => 'Aria answers questions about how LevelUpGrowth works: what a feature does, where it lives in Basic or Advanced, what each plan includes, what something costs in credits. She answers from the platform documentation and the plans table, reads only your plan name and credit balance, and says so when the documentation does not cover a question.',
            'fine' => 'In the sidebar on every plan, in both Basic and Advanced. Conversation is metered like every chat on the platform: one credit for every ten messages.',
            'off_note' => 'Documentation answers (no chat credits)',
            'capabilities' => [['Knows the platform', 'What each feature does, where it is in the app, what every plan includes, from the same documentation and plans table the platform enforces.'], ['Knows your plan', 'Your plan name and credit balance, so “what does my plan include” gets a real answer.'], ['Hands off to Sarah and Arthur', 'When you want work done, one tap sends the request to Sarah, or to Arthur for your website.']],
            'limit' => 'Aria explains; she never executes work, spends credits on tasks or changes settings.',
            'faq' => [['Is Aria the same as Sarah?', 'No. Sarah runs the workforce and does the work; Aria answers questions about the platform and points you to Sarah or Arthur when you want something done.'], ['Does Aria cost credits?', 'Conversation is metered like every chat on the platform: one credit for every ten messages. When a workspace has no credits, Aria still shows the documentation answer.'], ['Can Aria see my customers\' data?', 'No. Aria reads only your plan name and credit balance; everything else comes from the platform documentation.']]],
    ],
    'infrastructure' => [
        ['slug' => 'domains', 'icon' => 'globe', 'name' => 'Domains', 'engine' => 'Domain commerce', 'flag' => 'custom_domain',
            'promise' => 'Search, buy and connect your domain from inside your account.',
            'lede' => 'Search for a domain, see the price, pay, and it is registered to you and connected to your site with SSL.',
            'capabilities' => [['Registered to you', 'The registrant is your business, not us.'], ['Connected in one step', 'Your site answers on the domain with SSL provisioned automatically.'], ['Renewals you control', 'Auto-renew on or off, from the domain itself.']],
            'limit' => 'Transfers of existing domains are handled by request.',
            'faq' => [['What does a .com cost?', 'The price is shown at search time and includes the first year.'], ['Can I bring my own domain?', 'Yes, connect it from your site settings.'], ['Who owns it?', 'You do.']]],
        // RISK-0132 (DEC-0043 §3, 2026-09-07): not delivered today — no provider connector, no plan entitlement. Qualified, not sold.
        ['slug' => 'business-email', 'icon' => 'mail', 'name' => 'Business email', 'engine' => 'Business email', 'flag' => 'business_email', 'status' => 'coming_soon',
            'promise' => 'Business email on your domain is coming soon.',
            'lede' => 'Mailboxes, aliases and forwarders on your own domain are planned, not yet available: nothing is sold or provisioned today, and no current plan includes it. Your existing email provider keeps working when you connect a domain here.',
            'capabilities' => [['Coming soon', 'Mailboxes, aliases and forwarders on your domain are planned; they cannot be created from your account today.'], ['Your current email is untouched', 'Connecting a domain here does not change where your mail is hosted.'], ['Tell us you want it', 'Ask from the contact page and we will let you know when it is available.']],
            'limit' => 'Business email is not available yet: no mailbox can be created from your account today, and no plan includes it.',
            'faq' => [['Is business email available now?', 'No. It is coming soon and is not included in current plans.'], ['Can I keep using Gmail, Outlook or my current provider?', 'Yes. Connecting a domain here does not change your mail.'], ['How will I know when it ships?', 'Tell us you want it from the contact page and we will let you know.']]],
        // RISK-0132 (DEC-0043 §3, 2026-09-07): the Builder's included hosting is real; a managed runtime on the customer's own domain is not delivered today. Qualified, not sold.
        ['slug' => 'hosting', 'icon' => 'server', 'name' => 'Managed hosting', 'engine' => 'Managed hosting', 'flag' => 'hosting_access', 'status' => 'coming_soon',
            'promise' => 'Managed hosting on your own domain is coming soon.',
            'lede' => 'Every plan already includes hosting for the site you build here, with SSL, on a LevelUp subdomain. Managed hosting on your own domain, with a dedicated runtime, custom-domain SSL and priority deployment, is a separate service that is coming soon and is not included in current plans.',
            'capabilities' => [['Included today', 'Your site is hosted with SSL on a LevelUp subdomain on every plan, at no extra cost.'], ['Coming soon', 'A managed runtime on your own domain with custom-domain SSL and priority deployment, as a separate service.'], ['Tell us you want it', 'Ask from the contact page and we will let you know when it is available.']],
            'limit' => 'Managed hosting is not available yet: no plan includes it today, and it cannot be ordered from your account.',
            'faq' => [['Is hosting included on every plan?', 'Yes: subdomain hosting with SSL is included on every plan. Managed hosting on your own domain is a separate service that is coming soon.'], ['Can I use my own domain today?', 'Custom domains are available on the plans that include them; managed hosting is not needed for that.'], ['Can I move away?', 'Export the site at any time.']]],
    ],
];
