<?php
declare(strict_types=1);
/**
 * SOLUTIONS-2 (Owner 2026-10-03: "Solutions ... scored 2/10, make it enterprise level per industry"). One record per industry:
 * the outcome promise, what holds the industry back and how the platform answers it, the system in four parts, the five
 * specialists we recommend beside Sarah (every AI plan is Sarah + 5 you choose) and their job in this industry, the first
 * thirty days, the dashboard an owner sees (illustrative figures, labelled as an example), plan fit and questions.
 * Every claim maps to a shipped engine; the limits stay stated (no checkout, no room inventory, no portal syndication).
 */
return [
    ['slug' => 'restaurants', 'template' => 'restaurant', 'name' => 'Restaurants and cafes', 'short' => 'Restaurants', 'icon' => 'building', 'unit' => 'venue',
        'promise' => 'Full tables from search and social, booked without a phone call.',
        'lede' => 'A restaurant site that sells the room and the menu, takes bookings around the clock and ranks for the searches hungry people make, with an AI team that keeps your social calendar, your local listings and your guests moving every week.',
        'outcomes' => ['Rank for "near me" and cuisine searches', 'Bookings straight from the site and the chatbot', 'A month of social, drafted for your approval'],
        'pains' => [
            ['Guests book through someone else', 'Directories and delivery apps own the relationship and take a cut.', 'Your own site takes the booking and every guest lands in your CRM, yours to invite back.'],
            ['Quiet nights you could have filled', 'Social goes silent when service gets busy, and the room stays half empty midweek.', 'Marcus plans thirty days ahead and Maya drafts every post; you approve the queue in minutes.'],
            ['Questions that interrupt service', 'Hours, allergens, private hire: the phone rings while the kitchen is at its busiest.', 'The website chatbot answers from your menu and policies and hands real enquiries to you.'],
        ],
        'pillars' => [['search', 'Be found', 'Local search, Google profile signals and cuisine keywords handled for you.', ['seo']], ['calendar', 'Take the booking', 'Online booking and a chatbot that answers before guests give up.', ['calendar', 'chatbot']], ['share', 'Stay top of mind', 'Seasonal menus and specials on every channel, every week.', ['social', 'creative']], ['users', 'Bring them back', 'Every guest in one place, ready for the next occasion.', ['crm']]],
        'team' => [['diana', 'Keeps your local listings and "near me" signals strong.'], ['marcus', 'Plans the month of social around your menu and events.'], ['maya', 'Writes the captions and posts for every channel.'], ['priya', 'Writes the seasonal menu and private hire pages.'], ['elena', 'Keeps every booking and enquiry tidy in the CRM.']],
        'weeks' => [['Site and bookings live', 'Arthur builds the site with your menu, hours and location; online booking works on day one.'], ['Local search', 'Diana sets the local signals and maps the "near me" and cuisine searches worth winning.'], ['A month of social', 'Marcus plans thirty days and Maya drafts each post with images in your brand, all waiting for your yes.'], ['The chatbot and first pages', 'The chatbot answers menu, hours and booking questions; Priya writes the private hire page.']],
        'dash' => [['Bookings this month', '186'], ['From search', '41%'], ['Chatbot answers', '312'], ['Posts approved', '24']],
        'tasks' => [['marcus', 'Friday specials post', 'Waiting for you'], ['priya', 'Private hire page', 'Approved'], ['diana', 'Local listing refresh', 'Live']],
        'fit' => ['One restaurant or cafe', 'Several venues or brands', 'A group or franchise'],
        'faq' => [['Can guests book from the site?', 'Yes, from the booking section and from a shareable link; every booking lands in your CRM with the guest\'s details.'], ['Do you write the menu?', 'You supply it; Arthur lays it out and the team writes around it, from dish descriptions to seasonal specials.'], ['Will anything post without me?', 'No. Every post, page and reply waits for your approval before it goes live.'], ['Can it handle more than one venue?', 'Yes. Growth runs three websites and businesses, Pro runs ten, each with its own brand and calendar.']]],

    ['slug' => 'gyms', 'template' => 'gym', 'name' => 'Gyms and fitness studios', 'short' => 'Gyms', 'icon' => 'zap', 'unit' => 'studio',
        'promise' => 'Turn class schedules and transformations into members.',
        'lede' => 'A site built for programmes, coaches, timetables and trial sign-ups, with an AI team that fills your social with reels and results, follows up every trial and keeps your studio visible in local search.',
        'outcomes' => ['Trial sign-ups straight into your CRM', 'Reels and short video, scripted for you', 'Follow-up that turns trials into members'],
        'pains' => [
            ['Trials that never convert', 'People sign up for a free class and are never heard from again.', 'Kai sets the follow-up rules, so every trial gets the right message at the right time, approved by you.'],
            ['Content that never gets made', 'Coaches coach. Nobody has time to script, film and post.', 'Chris writes the scripts and Zoe shapes the reels; you film or approve what the Studio produces.'],
            ['Invisible to people nearby', 'New residents search "gym near me" and find the chains first.', 'Diana strengthens your local signals and keeps your listings consistent everywhere.'],
        ],
        'pillars' => [['search', 'Be found', 'Local search and the keywords people use before they join.', ['seo']], ['calendar', 'Book the first class', 'Timetables, trial sign-ups and reminders that go out on their own.', ['calendar', 'crm']], ['video', 'Show the results', 'Reels, transformations and short video, ready for approval.', ['video', 'social']], ['users', 'Keep members', 'Nurture rules that bring people back before they drift.', ['automation']]],
        'team' => [['marcus', 'Plans the month of social around your classes.'], ['zoe', 'Shapes reels and short-form video for every channel.'], ['chris', 'Writes the video scripts for transformations and coaches.'], ['kai', 'Follows up every trial until it becomes a membership.'], ['diana', 'Keeps your studio visible in local search.']],
        'weeks' => [['Site, timetable, sign-ups', 'Arthur builds the site with programmes, coaches and the class timetable; trial sign-ups go straight to the CRM.'], ['Local search', 'Diana sets the local signals and the searches people make before joining a gym.'], ['Reels and social', 'Marcus plans the month; Chris scripts and Zoe shapes the short videos for your approval.'], ['Trial follow-up', 'Kai sets the nurture rules for every trial, so nobody slips through.']],
        'dash' => [['Trial sign-ups', '58'], ['Trials to members', '34%'], ['Reels published', '12'], ['Classes booked', '420']],
        'tasks' => [['chris', 'Transformation reel script', 'Waiting for you'], ['kai', 'Trial day-3 follow-up', 'Live'], ['marcus', 'January challenge campaign', 'Approved']],
        'fit' => ['One studio', 'Several studios or brands', 'A chain or franchise'],
        'faq' => [['Can members book classes?', 'Yes, through the calendar, with reminders sent automatically.'], ['Do you produce video?', 'Chris writes the scripts and the Studio assembles short videos; nothing publishes until you approve it.'], ['Will it chase trial sign-ups?', 'Yes. Follow-up rules you approve send the right message after each trial.'], ['Can I run several locations?', 'Yes. Growth covers three websites and businesses and Pro covers ten, each with its own timetable.']]],

    ['slug' => 'dental-and-medical', 'template' => 'dental', 'name' => 'Dental and medical clinics', 'short' => 'Clinics', 'icon' => 'shield', 'unit' => 'clinic',
        'promise' => 'Be found for the treatments you offer, and book the consultation.',
        'lede' => 'A clinic site with treatments, practitioners and appointment booking, written carefully and kept accurate, with local search, patient education and front-desk questions handled for you.',
        'outcomes' => ['Rank for the treatments you offer', 'Consultations booked online', 'Careful, reviewed patient content'],
        'pains' => [
            ['Patients choose who they find first', 'Treatment searches go to clinics with stronger local signals.', 'Diana and James map the treatment searches in your area and strengthen your local presence.'],
            ['A front desk stuck on the phone', 'Hours, insurance and "do you treat this?" fill the day.', 'The website chatbot answers from your own information and hands bookings to the desk.'],
            ['Content that has to be right', 'Health content cannot overpromise, and there is no time to write it.', 'Priya writes from your briefs, the review gate rejects unsupported claims, and you approve every piece.'],
        ],
        'pillars' => [['search', 'Be found', 'Treatment keywords and local search, mapped and maintained.', ['seo']], ['calendar', 'Book the consultation', 'Online appointments that land in your CRM.', ['calendar', 'crm']], ['pen', 'Educate patients', 'Treatment explainers written carefully and reviewed.', ['content']], ['message', 'Answer around the clock', 'A chatbot for the questions your desk answers every day.', ['chatbot']]],
        'team' => [['diana', 'Keeps the clinic visible for local treatment searches.'], ['james', 'Maps the treatments patients search for.'], ['priya', 'Writes careful, reviewed treatment explainers.'], ['elena', 'Keeps appointments and enquiries organised.'], ['kai', 'Sends the reminders and recall messages you approve.']],
        'weeks' => [['Site and appointments', 'Arthur builds the site with treatments, practitioners and hours; consultation booking is live.'], ['Search foundations', 'Diana sets the local signals and James maps the treatment searches worth winning.'], ['Patient content', 'Priya writes treatment explainers from your briefs; each passes the review gate before you see it.'], ['The front desk online', 'The chatbot answers hours, insurance and booking questions and hands real enquiries to the desk.']],
        'dash' => [['Consultations booked', '74'], ['Treatment keywords', '26'], ['Chatbot answers', '268'], ['Recalls sent', '140']],
        'tasks' => [['priya', 'Invisalign explainer', 'Waiting for you'], ['diana', 'Practitioner listings', 'Live'], ['kai', 'Six-month recall', 'Approved']],
        'fit' => ['One clinic', 'Several clinics or practices', 'A healthcare group'],
        'faq' => [['Will the content make medical claims?', 'The review gate rejects unsupported claims, and you approve every piece before it publishes.'], ['Can patients book online?', 'Yes, and each appointment is recorded in the CRM.'], ['Can the chatbot give medical advice?', 'No. It answers practical questions from your information and directs clinical questions to your team.'], ['Do you handle several practices?', 'Yes. Growth covers three websites and businesses, Pro covers ten, each with its own practitioners and hours.']]],

    ['slug' => 'real-estate', 'template' => 'real_estate_agency', 'name' => 'Real estate', 'short' => 'Real estate', 'icon' => 'building', 'unit' => 'agency',
        'promise' => 'An agency presence that ranks, captures enquiries and follows up every lead.',
        'lede' => 'A listings-ready agency site with valuation and enquiry capture wired to your CRM, follow-up rules that never forget a lead, and market content that makes you the name buyers and sellers search for.',
        'outcomes' => ['Valuation and viewing requests captured', 'Follow-up that never forgets a lead', 'Area guides that rank for your patch'],
        'pains' => [
            ['Leads that go cold', 'Enquiries arrive at all hours and the fastest agent wins.', 'Vera and Elena set follow-up rules that respond at once and keep every lead moving, with your approval.'],
            ['Portals own the audience', 'Buyers and sellers meet you on someone else\'s platform.', 'Area guides and market notes rank for your patch and bring people to your own site.'],
            ['Authority takes time you do not have', 'Market updates and LinkedIn presence slip behind viewings.', 'Priya writes the market content and Tyler drafts your LinkedIn, ready for your yes.'],
        ],
        'pillars' => [['search', 'Own your area', 'Area and property-type searches, mapped and won.', ['seo', 'content']], ['users', 'Capture every enquiry', 'Valuation, viewing and contact forms straight into the CRM.', ['crm']], ['zap', 'Follow up instantly', 'Rules that answer and remind, approved once by you.', ['automation']], ['share', 'Build your name', 'LinkedIn and social that make you the local expert.', ['social']]],
        'team' => [['james', 'Maps the area and property searches worth winning.'], ['priya', 'Writes the area guides and market notes.'], ['tyler', 'Drafts your LinkedIn presence as the local expert.'], ['vera', 'Builds the follow-up rules for every type of lead.'], ['elena', 'Keeps the pipeline clean, from enquiry to instruction.']],
        'weeks' => [['Site and enquiries', 'Arthur builds the agency site with areas, services and valuation forms wired to the CRM.'], ['Search', 'James maps the area and property-type searches; the site is built to win them.'], ['Market content', 'Priya writes the first area guides and market notes from your briefs.'], ['Follow-up and LinkedIn', 'Vera sets the follow-up rules and Tyler drafts the first month of LinkedIn content.']],
        'dash' => [['Enquiries captured', '96'], ['Valuations booked', '18'], ['Area guides ranking', '9'], ['Follow-ups sent', '312']],
        'tasks' => [['tyler', 'Q4 market update post', 'Waiting for you'], ['vera', 'Valuation follow-up rule', 'Live'], ['priya', 'Riverside area guide', 'Approved']],
        'fit' => ['One office', 'Several offices or brands', 'A network or franchise'],
        'faq' => [['Can I show listings?', 'Arthur builds listing sections you fill; portal syndication is not part of the product.'], ['Does it follow up leads?', 'Yes. Rules you approve send confirmations and reminders, and the team drafts the rest for approval.'], ['Will LinkedIn post on its own?', 'No. Tyler drafts the posts and each one waits for your approval.'], ['Can each office have its own site?', 'Yes. Growth covers three websites and businesses, Pro covers ten.']]],

    ['slug' => 'beauty-and-barbers', 'template' => 'beauty_salon', 'name' => 'Salons and barbershops', 'short' => 'Salons', 'icon' => 'image', 'unit' => 'salon',
        'promise' => 'A full book of appointments and a feed people want to follow.',
        'lede' => 'A salon site with services, stylists, prices and online booking, plus the Instagram presence your business lives on, produced every month for your approval, and reminders that bring clients back on time.',
        'outcomes' => ['Online booking, day and night', 'Instagram and reels every week', 'Rebooking reminders on time'],
        'pains' => [
            ['The feed goes quiet', 'You are with clients all day, so posting waits until it is forgotten.', 'Zara grows your Instagram and Maya drafts every caption; you approve the month at once.'],
            ['Gaps in the book', 'Clients mean to rebook and forget, and the empty chair costs you.', 'Kai sets reminders and rebooking prompts that go out at the right time.'],
            ['Walk-ins go elsewhere', 'People nearby search for a salon and find the one with the stronger profile.', 'Diana keeps your local listings and searches strong.'],
        ],
        'pillars' => [['image', 'Look the part', 'A feed and site that show your work at its best.', ['social', 'creative']], ['calendar', 'Fill the book', 'Online booking with services, prices and stylists.', ['calendar']], ['search', 'Be found nearby', 'Local search and listings, handled.', ['seo']], ['zap', 'Bring them back', 'Reminders and rebooking prompts that run themselves.', ['automation', 'crm']]],
        'team' => [['zara', 'Grows your Instagram with the looks you create.'], ['maya', 'Writes the captions and stories every week.'], ['marcus', 'Plans the month around seasons and offers.'], ['diana', 'Keeps you first for nearby salon searches.'], ['kai', 'Sends rebooking prompts and reminders on time.']],
        'weeks' => [['Site and bookings', 'Arthur builds the site with services, prices and stylists; online booking is live.'], ['Local search', 'Diana sets the local signals for the searches that bring walk-ins.'], ['A visual month', 'Marcus plans it, Zara and Maya draft the posts with images in your brand, all for your approval.'], ['Reminders and rebooking', 'Kai sets the reminder and rebooking rules so the book stays full.']],
        'dash' => [['Appointments booked', '214'], ['Rebooked on time', '61%'], ['Posts approved', '28'], ['New followers', '+380']],
        'tasks' => [['zara', 'Balayage carousel', 'Waiting for you'], ['kai', 'Six-week rebooking prompt', 'Live'], ['maya', 'Weekend offer stories', 'Approved']],
        'fit' => ['One salon or barbershop', 'Several locations or brands', 'A salon group'],
        'faq' => [['Can clients pick a stylist?', 'Stylist choice is captured in the booking notes, so your team sees it with each appointment.'], ['Do you post for me?', 'Everything is drafted and scheduled for your approval and posts through the channels you connect.'], ['Will reminders go out automatically?', 'Yes, once you approve the rules; you can pause them any time.'], ['Can each location have its own page?', 'Yes. Growth covers three websites and businesses, Pro covers ten.']]],

    ['slug' => 'consulting', 'template' => 'consulting', 'name' => 'Consulting and professional services', 'short' => 'Professional services', 'icon' => 'users', 'unit' => 'firm',
        'promise' => 'Thought leadership, consultations booked and a pipeline you own.',
        'lede' => 'A credible firm site with services, sectors, case studies and consultation booking, and an AI team that writes the thought leadership your clients search for, runs your LinkedIn and keeps the pipeline moving.',
        'outcomes' => ['Consultations booked from your site', 'Thought leadership every month', 'A LinkedIn presence that compounds'],
        'pains' => [
            ['Expertise nobody can find', 'Clients search their problem, not your name, and find someone else.', 'Nora sets the content strategy around the problems your clients search, and James maps those searches.'],
            ['No time to write', 'Billable work always wins over the article you meant to publish.', 'Priya writes from your briefs in your voice, and every piece passes review before you see it.'],
            ['A pipeline in your inbox', 'Enquiries scatter across email and are hard to follow up.', 'Elena keeps every enquiry and consultation in one CRM, ready for the next step.'],
        ],
        'pillars' => [['pen', 'Lead the conversation', 'Articles and insights on the problems your clients have.', ['content']], ['share', 'Build your name', 'A LinkedIn presence drafted every week.', ['social']], ['calendar', 'Book the consultation', 'Consultation booking straight from the site.', ['calendar']], ['users', 'Own the pipeline', 'Every enquiry tracked from first contact to engagement.', ['crm']]],
        'team' => [['nora', 'Sets the content strategy around your clients\' problems.'], ['priya', 'Writes the insights and case studies in your voice.'], ['tyler', 'Drafts your LinkedIn presence every week.'], ['james', 'Maps the problem-led searches your clients make.'], ['elena', 'Runs the pipeline from enquiry to engagement.']],
        'weeks' => [['Site and consultation booking', 'Arthur builds the site with services, sectors and approach, with consultation booking.'], ['The keyword map', 'James maps the problem-led searches your clients make before they hire.'], ['Thought leadership', 'Nora sets the plan and Priya writes the first insights from your briefs.'], ['LinkedIn and pipeline', 'Tyler drafts the first month of LinkedIn and Elena sets up the pipeline.']],
        'dash' => [['Consultations booked', '22'], ['Insights published', '6'], ['LinkedIn reach', '14.2k'], ['Pipeline value', '$380k']],
        'tasks' => [['priya', 'Insight: pricing strategy', 'Waiting for you'], ['tyler', 'LinkedIn: client lesson', 'Approved'], ['elena', 'Proposal follow-up', 'Live']],
        'fit' => ['A practice or boutique firm', 'Several practices or brands', 'A national or global firm'],
        'faq' => [['Will the writing sound like me?', 'You set the tone once; the review gate checks every piece against it, and you approve before anything publishes.'], ['Do you send proposals?', 'No. The CRM tracks the pipeline; proposals stay yours.'], ['Can we publish case studies?', 'Yes, written from what you share and approved by you before they go live.'], ['We are a large firm. Is there more?', 'Yes. Enterprise engagements are built around your strategy and every department.']]],

    ['slug' => 'retail', 'template' => 'retail_shop', 'name' => 'Retail and product brands', 'short' => 'Retail', 'icon' => 'layers', 'unit' => 'store',
        'promise' => 'A brand site, product content and creatives that keep up with every season.',
        'lede' => 'A retail site with collections and a brand story, with product copy, campaign creatives and a social calendar produced on schedule, and a chatbot that answers sizing, delivery and stock questions from your own knowledge.',
        'outcomes' => ['Collections and product copy, on brand', 'Campaign creatives in every size', 'A chatbot for sizing and delivery questions'],
        'pains' => [
            ['Every season needs new everything', 'New collections mean new copy, new images and new posts, every time.', 'Leo and Priya write the collection and product copy, and the creative engine makes the images.'],
            ['A brand voice that drifts', 'Different hands, different tones, and the brand blurs.', 'Leo keeps one brand voice across every page, post and caption.'],
            ['The same questions, all day', 'Sizing, delivery and returns questions keep customers waiting.', 'The website chatbot answers from your documents and passes real enquiries to you.'],
        ],
        'pillars' => [['layers', 'Tell the brand story', 'Collections, story and product pages that sell.', ['website-builder', 'content']], ['image', 'Launch every season', 'Campaign creatives in every channel size.', ['creative']], ['share', 'Stay in the feed', 'A social calendar built around drops and offers.', ['social']], ['message', 'Answer shoppers', 'A chatbot for sizing, delivery and stock questions.', ['chatbot']]],
        'team' => [['leo', 'Keeps one brand voice across everything you publish.'], ['priya', 'Writes collection and product copy every season.'], ['zara', 'Grows your Instagram around each drop.'], ['marcus', 'Plans the social calendar around launches and offers.'], ['james', 'Maps the product searches shoppers make.']],
        'weeks' => [['Brand site', 'Arthur builds the site with collections, brand story and contact.'], ['Product content', 'Leo sets the brand voice and Priya writes the collection and product copy.'], ['Campaign creatives', 'The creative engine produces images in every channel size; Marcus plans the calendar.'], ['Search and the chatbot', 'James maps product searches and the chatbot answers sizing, delivery and stock questions.']],
        'dash' => [['Product pages live', '64'], ['Creatives approved', '48'], ['Chatbot answers', '530'], ['Enquiries captured', '87']],
        'tasks' => [['leo', 'Autumn collection story', 'Waiting for you'], ['zara', 'New drop carousel', 'Approved'], ['priya', '12 product descriptions', 'Live']],
        'fit' => ['One store or brand', 'Several stores or brands', 'A retail group'],
        'faq' => [['Is there a checkout?', 'The site presents products and captures enquiries; online checkout is not part of the builder.'], ['Can the chatbot answer product questions?', 'Yes, from the documents and pages you give it.'], ['Can you keep up with new collections?', 'Yes. Each season the team drafts the copy and creatives for your approval.'], ['Do you support several brands?', 'Yes. Growth covers three websites and businesses, Pro covers ten, each with its own brand.']]],

    ['slug' => 'hotels-and-rentals', 'template' => 'hotel', 'name' => 'Hotels and short-term rentals', 'short' => 'Hospitality', 'icon' => 'calendar', 'unit' => 'property',
        'promise' => 'Direct enquiries from search, and a site that sells the stay.',
        'lede' => 'A hospitality site that shows the rooms, the amenities and the place, ranks for destination searches at home and abroad, and captures direct enquiries you pay no commission on, with follow-up that turns interest into stays.',
        'outcomes' => ['Direct enquiries without commission', 'Ranking for destination searches, worldwide', 'Follow-up that turns interest into stays'],
        'pains' => [
            ['Commission on every stay', 'Booking platforms own the guest and take a share of every night.', 'Your own site wins direct enquiries, and every guest lands in your CRM for the next stay.'],
            ['Guests search in many languages', 'Travellers search the destination in their own language and market.', 'Sofia handles international search and James maps the destination and stay-type searches.'],
            ['Enquiries that wait too long', 'A question about dates goes unanswered overnight and the guest books elsewhere.', 'The chatbot answers at once and Kai sets the follow-up rules for every enquiry.'],
        ],
        'pillars' => [['globe', 'Be found worldwide', 'Destination and international search, mapped and won.', ['seo']], ['image', 'Sell the stay', 'Rooms, amenities and the place, shown at their best.', ['website-builder', 'creative']], ['message', 'Answer at once', 'A chatbot for dates, rooms and policies.', ['chatbot']], ['users', 'Turn interest into stays', 'Every enquiry followed up and every guest remembered.', ['crm', 'automation']]],
        'team' => [['sofia', 'Wins destination searches in your international markets.'], ['james', 'Maps the destination and stay-type searches.'], ['priya', 'Writes the destination guides and room pages.'], ['marcus', 'Plans the social calendar around seasons and events.'], ['kai', 'Follows up every enquiry until it becomes a stay.']],
        'weeks' => [['Site and enquiries', 'Arthur builds the site with rooms, amenities, location and an enquiry form into the CRM.'], ['Destination search', 'Sofia and James map the destination and stay-type searches, at home and abroad.'], ['Guides and social', 'Priya writes destination guides and Marcus plans the calendar with images in your brand.'], ['Enquiry follow-up', 'Kai sets the follow-up rules and the chatbot answers dates and room questions.']],
        'dash' => [['Direct enquiries', '132'], ['Markets ranking', '5'], ['Chatbot answers', '406'], ['Enquiries to stays', '27%']],
        'tasks' => [['sofia', 'German destination page', 'Waiting for you'], ['kai', 'Enquiry day-2 follow-up', 'Live'], ['priya', 'Winter breaks guide', 'Approved']],
        'fit' => ['One hotel or rental', 'Several properties or brands', 'A hotel group'],
        'faq' => [['Is there a booking engine?', 'Enquiries and booking requests are captured; live room inventory and payment are not part of the product.'], ['Can I list on portals?', 'Portal syndication is outside the platform; the site is built to win direct enquiries.'], ['Do you handle other languages?', 'Sofia plans international search for the markets you choose, so travellers abroad find you when they search the destination.'], ['Can I run several properties?', 'Yes. Growth covers three websites and businesses, Pro covers ten.']]],
];
