<?php
declare(strict_types=1);
/**
 * Eight industry solutions. Each maps to a template slug, names the agent categories that matter, lists the
 * products used (product-data slugs) and lays out a first-30-days plan by week, every step on a certified engine.
 */
return [
    ['slug' => 'restaurants', 'template' => 'restaurant', 'name' => 'Restaurants and cafes', 'icon' => 'building',
        'promise' => 'Fill tables from search and social, and take bookings without a phone call.',
        'lede' => 'A restaurant site that shows the menu, takes bookings and ranks for "near me" searches, with a workforce that keeps the content and the social calendar moving every week.',
        'agents' => ['seo', 'content', 'social'], 'products' => ['website-builder', 'calendar', 'seo', 'social', 'chatbot', 'creative'],
        'weeks' => [['Site and bookings live', 'Arthur builds the restaurant site with your menu, hours and location; the booking section is live on day one.'], ['Local search', 'Diana sets the local signals and Alex clears the technical audit; James maps the "near me" and cuisine keywords.'], ['A month of social', 'Marcus plans thirty days; Maya and Zoe draft per channel with creative-engine images; you approve the queue.'], ['First articles and the chatbot', 'Priya writes the first two briefed articles; the chatbot answers menu, hours and booking questions on the site.']],
        'faq' => [['Can guests book from the site?', 'Yes, from the booking section and from a shareable link; each booking lands in the CRM.'], ['Do you write the menu?', 'You supply it; Arthur lays it out and the content team writes around it.']]],
    ['slug' => 'gyms', 'template' => 'gym', 'name' => 'Gyms and fitness studios', 'icon' => 'zap',
        'promise' => 'Turn class schedules and transformations into members.',
        'lede' => 'A site built for programmes, trainers, schedules and sign-ups, with a workforce that keeps the transformations gallery, the blog and the social calendar full.',
        'agents' => ['seo', 'content', 'social', 'crm'], 'products' => ['website-builder', 'calendar', 'crm', 'social', 'creative', 'video'],
        'weeks' => [['Site, schedule, sign-ups', 'Arthur builds the gym site with your programmes, trainers and class schedule; trial sign-ups go to the CRM.'], ['Local search and reviews', 'Diana on local signals, James on the keywords people search before joining a gym.'], ['Social and short video', 'Marcus plans the month; Zoe and Chris produce reels and scripts in the Studio for approval.'], ['Nurture', 'Kai sets the follow-up rules for trial sign-ups; Elena keeps the pipeline clean.']],
        'faq' => [['Can members book classes?', 'Yes, through the calendar; reminders go out automatically.'], ['Do you produce video?', 'Scripted by Chris, assembled in the Studio, approved by you.']]],
    ['slug' => 'dental-and-medical', 'template' => 'dental', 'name' => 'Dental and medical clinics', 'icon' => 'shield',
        'promise' => 'Be found for the treatments you offer and book the consultation.',
        'lede' => 'A clinic site with services, practitioners and appointment booking, written carefully and kept accurate, with local search handled for you.',
        'agents' => ['seo', 'content', 'crm'], 'products' => ['website-builder', 'calendar', 'seo', 'content', 'chatbot', 'crm'],
        'weeks' => [['Site and appointments', 'Arthur builds the clinic site with services, practitioners and hours; consultation booking is live.'], ['Technical and local SEO', 'Alex clears the audit, Diana sets the local signals, James maps treatment keywords.'], ['Patient content', 'Priya writes treatment explainers from briefs; every article passes the review gate before you see it.'], ['Front desk online', 'The chatbot answers hours, insurance and booking questions and hands off to the desk.']],
        'faq' => [['Will the content make medical claims?', 'The review gate rejects unsupported claims; you approve every piece before it publishes.'], ['Can patients book online?', 'Yes, and each booking is recorded in the CRM.']]],
    ['slug' => 'real-estate', 'template' => 'real_estate_agency', 'name' => 'Real estate', 'icon' => 'building',
        'promise' => 'A broker profile that ranks, captures enquiries and follows up.',
        'lede' => 'A listings-ready profile site with enquiry capture and follow-up rules, and a workforce that produces the market content buyers search for.',
        'agents' => ['seo', 'content', 'crm', 'social'], 'products' => ['website-builder', 'crm', 'automation', 'seo', 'content', 'social'],
        'weeks' => [['Profile and enquiries', 'Arthur builds the brokerage site with areas, services and enquiry forms wired to the CRM.'], ['Search', 'James maps area and property-type keywords; Diana handles local signals.'], ['Market content', 'Priya and Leo write area guides and market notes from briefs.'], ['Follow-up', 'Vera sets the automation rules; Max reviews conversion; LinkedIn content from Tyler.']],
        'faq' => [['Can I show listings?', 'Arthur builds listing sections you fill; portal syndication is not part of the product.'], ['Does it follow up leads?', 'Rules you approve send the confirmations and reminders; the workforce drafts the rest for approval.']]],
    ['slug' => 'beauty-and-barbers', 'template' => 'beauty_salon', 'name' => 'Salons and barbershops', 'icon' => 'image',
        'promise' => 'Bookings from the site, a full social calendar, no agency.',
        'lede' => 'A salon site with services, stylists and online booking, plus the social presence the business depends on, produced every month for your approval.',
        'agents' => ['social', 'seo', 'crm'], 'products' => ['website-builder', 'calendar', 'social', 'creative', 'chatbot', 'crm'],
        'weeks' => [['Site and bookings', 'Arthur builds the salon site with services, prices and stylists; booking live.'], ['Local search', 'Diana and James on the searches that bring walk-ins.'], ['A visual month', 'Zara and Zoe draft Instagram and short-form content with creative-engine images; you approve.'], ['Reminders and repeat visits', 'Automation rules for reminders and rebooking prompts.']],
        'faq' => [['Can clients pick a stylist?', 'Availability is per workspace; stylist choice can be captured in the booking notes.'], ['Do you post for me?', 'Everything is drafted and scheduled for your approval and posts through the channels you connect.']]],
    ['slug' => 'consulting', 'template' => 'consulting', 'name' => 'Consulting and professional services', 'icon' => 'users',
        'promise' => 'Authority content, consultation bookings, a pipeline you own.',
        'lede' => 'A credible site with services, case studies and consultation booking, and a workforce that writes the thought leadership your clients search for.',
        'agents' => ['content', 'seo', 'crm', 'social'], 'products' => ['website-builder', 'content', 'seo', 'calendar', 'crm', 'social'],
        'weeks' => [['Site and consultation booking', 'Arthur builds the consultancy site with services, approach and a booking section.'], ['Keyword map', 'James and Sofia map the problem-led searches your clients make.'], ['Authority content', 'Nora sets the content strategy; Priya and Leo write from briefs; every piece reviewed before you see it.'], ['LinkedIn and pipeline', 'Tyler drafts LinkedIn content; Elena and Kai run the pipeline and follow-ups.']],
        'faq' => [['Will the writing sound like me?', 'You set the tone once; the review gate checks alignment on every piece; you approve before publish.'], ['Do you send proposals?', 'No. The CRM tracks the pipeline; proposals are yours.']]],
    ['slug' => 'retail', 'template' => 'retail_shop', 'name' => 'Retail and product brands', 'icon' => 'layers',
        'promise' => 'A brand site, product content and creatives that keep up with the season.',
        'lede' => 'A retail site with collections and a brand story, with product descriptions, creatives and social content produced on schedule.',
        'agents' => ['content', 'social', 'seo'], 'products' => ['website-builder', 'content', 'creative', 'social', 'seo', 'chatbot'],
        'weeks' => [['Brand site', 'Arthur builds the brand site with collections, story and contact.'], ['Product content', 'Priya writes collection and product copy from briefs; Leo handles the brand voice.'], ['Creatives', 'The creative engine produces images in every channel size; Marcus plans the calendar.'], ['Search and support', 'James on product keywords; the chatbot answers sizing, shipping and stock questions from your knowledge.']],
        'faq' => [['Is there a checkout?', 'The site presents products and captures enquiries; online checkout is not part of the builder.'], ['Can the chatbot answer product questions?', 'Yes, from the documents and pages you give it.']]],
    ['slug' => 'hotels-and-rentals', 'template' => 'hotel', 'name' => 'Hotels and short-term rentals', 'icon' => 'calendar',
        'promise' => 'Direct enquiries from search and a site that sells the stay.',
        'lede' => 'A hospitality site that shows rooms, amenities and location, ranks for destination searches and captures direct enquiries you do not pay commission on.',
        'agents' => ['seo', 'content', 'social', 'crm'], 'products' => ['website-builder', 'seo', 'content', 'crm', 'social', 'creative'],
        'weeks' => [['Site and enquiries', 'Arthur builds the hotel site with rooms, amenities, location and an enquiry form into the CRM.'], ['Destination search', 'James and Sofia map destination and stay-type keywords; Alex clears the audit.'], ['Guides and social', 'Priya writes destination guides; Marcus plans the calendar with creative-engine images.'], ['Enquiry follow-up', 'Kai and Vera set the follow-up rules; Elena keeps the pipeline current.']],
        'faq' => [['Is there a booking engine?', 'Enquiries and booking requests are captured; live room inventory and payment are not part of the product.'], ['Can I list on portals?', 'Portal syndication is outside the platform; the site is built to win direct enquiries.']]],
];
