<?php

namespace App\Core\Email888\Console;

use App\Core\Email888\Models\WebhookReceipt;
use Illuminate\Console\Command;

/**
 * EMAIL888 EM-6 — bounded retention for webhook ingress receipts.
 *
 * WHY THE TWO WINDOWS ARE DIFFERENT
 * An accepted receipt is evidence about real mail we sent, and it is the only
 * record of when the provider told us. It is kept for a year. A refusal is
 * mostly somebody else's port scan — useful while diagnosing, worthless a month
 * later, and generated by anyone who can reach the URL. It is kept for thirty
 * days.
 *
 * WHAT IS NEVER PRUNED
 * The most recent receipt of every distinct kind survives regardless of age.
 * Deleting the last surviving `refused_unconfigured` row would erase the only
 * evidence that the endpoint was ever unconfigured, and "we have never seen
 * this" would silently replace "we saw it, in March". Retention must bound
 * volume, not rewrite history.
 */
class PruneWebhookReceipts extends Command
{
    protected $signature = 'email888:prune-receipts
                            {--dry-run : Report what would be deleted and delete nothing}';

    protected $description = 'EMAIL888: prune old webhook ingress receipts within bounded retention.';

    public function handle(): int
    {
        $dry         = (bool) $this->option('dry-run');
        $keepRefused = (int) config('email888.receipts.refused_retention_days', 30);
        $keepOk      = (int) config('email888.receipts.accepted_retention_days', 365);

        // The newest row of each kind is exempt, so no category can vanish
        // entirely just because it has been quiet.
        $keepIds = WebhookReceipt::selectRaw('MAX(id) as id')
            ->groupBy('authentication_result')
            ->pluck('id')
            ->all();

        $this->line(sprintf(
            'retention: refusals %d days, accepted %d days; %d row(s) exempt as the newest of their kind',
            $keepRefused, $keepOk, count($keepIds),
        ));

        $refused = WebhookReceipt::whereIn('authentication_result', WebhookReceipt::refusalReasons())
            ->where('received_at', '<', now()->subDays($keepRefused))
            ->whereNotIn('id', $keepIds);

        $accepted = WebhookReceipt::where('authentication_result', WebhookReceipt::AUTH_ACCEPTED)
            ->where('received_at', '<', now()->subDays($keepOk))
            ->whereNotIn('id', $keepIds);

        $nRefused  = (clone $refused)->count();
        $nAccepted = (clone $accepted)->count();

        if ($dry) {
            $this->line("would delete: {$nRefused} refusal(s), {$nAccepted} accepted");

            return self::SUCCESS;
        }

        $refused->delete();
        $accepted->delete();

        $this->line("deleted: {$nRefused} refusal(s), {$nAccepted} accepted");
        $this->line('remaining: ' . WebhookReceipt::count());

        return self::SUCCESS;
    }
}
