<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * A business profile inside a workspace (RFC-0011 U1). One row per workspace is the default; the workspaces.*
 * profile columns mirror it (see mirrorToWorkspace) so unrewired readers keep seeing today's values.
 */
class Business extends Model
{
    use SoftDeletes;

    /** The profile fields shared with workspaces.* (the mirror): workspaces column => businesses column. */
    public const MIRROR = ['business_name' => 'name', 'industry' => 'industry', 'services_json' => 'services_json', 'goal' => 'goal', 'location' => 'location', 'brand_color' => 'brand_color', 'logo_url' => 'logo_url'];

    /** Memory keys that are profile facts (portfolio-level today; biz:{id}:key per business). */
    public const MEMORY_FACTS = ['business_name', 'industry', 'location', 'services', 'tone', 'target_audience', 'differentiators', 'pricing_anchor', 'domain'];

    /**
     * K4 (2026-09-25) — the identity facts a machine-readable Organization needs.
     * These are what SchemaComposer may publish, and only when identity_meta_json
     * says the value is owner-stated, verified or imported.
     */
    public const IDENTITY_FIELDS = ['phone', 'email', 'address_json', 'opening_hours_json', 'sameas_json', 'area_served_json', 'founding_date', 'schema_type'];

    /** Provenance values allowed in identity_meta_json. Only the first three may be published. */
    public const SOURCE_PUBLISHABLE = ['owner_stated', 'verified', 'imported'];
    public const SOURCE_WITHHELD = ['observed', 'proposed', 'ai_generated'];

    protected $fillable = [
        'workspace_id', 'name', 'slug', 'aliases_json', 'industry', 'services_json', 'goal', 'location', 'brand_color', 'logo_url',
        'tone', 'target_audience', 'differentiators', 'pricing_anchor', 'settings_json', 'is_default', 'sort_order',
        'phone', 'email', 'address_json', 'opening_hours_json', 'sameas_json', 'area_served_json', 'founding_date', 'schema_type', 'identity_meta_json',
    ];

    protected $casts = [
        'aliases_json' => 'array', 'services_json' => 'array', 'settings_json' => 'array', 'is_default' => 'boolean',
        'address_json' => 'array', 'opening_hours_json' => 'array', 'sameas_json' => 'array',
        'area_served_json' => 'array', 'identity_meta_json' => 'array',
    ];

    /** The recorded source of one identity field, or null when nothing was recorded. */
    public function identitySource(string $field): ?string
    {
        $meta = $this->identity_meta_json ?? [];

        return $meta[$field]['source'] ?? null;
    }

    /**
     * May this field reach public structured data?
     *
     * A value with NO recorded source is treated as owner-stated: it can only
     * have been typed into Settings by the customer, because every automatic
     * writer stamps its provenance. A value proposed by the candidate scan, or
     * generated by a model, is withheld until someone confirms it.
     */
    public function identityIsPublishable(string $field): bool
    {
        $value = $this->{$field} ?? null;
        if ($value === null || $value === '' || $value === [] ) { return false; }
        $source = $this->identitySource($field);

        return $source === null || in_array($source, self::SOURCE_PUBLISHABLE, true);
    }

    /** Record where one identity value came from, without disturbing the others. */
    public function stampIdentitySource(string $field, string $source, ?string $from = null): void
    {
        $meta = $this->identity_meta_json ?? [];
        $meta[$field] = array_filter([
            'source' => $source,
            'from' => $from,
            'at' => now()->toIso8601String(),
        ], fn ($v) => $v !== null);
        $this->identity_meta_json = $meta;
    }

    public function workspace() { return $this->belongsTo(Workspace::class); }

    protected static function booted(): void
    {
        static::saved(function (Business $b) {
            if ($b->is_default) { $b->mirrorToWorkspace(); }
        });
    }

    /**
     * RFC-0011 (Owner rule 2026-09-22): a PUBLISHED website has exactly one profile. Create it (seeded from the
     * website) the first time the site is published; a draft has none. Idempotent. Returns the business id, or null
     * for a draft / missing website. The oldest profile in the workspace is the default (mirrors workspaces.*).
     */
    public static function ensureForWebsite(int $wsId, int $websiteId): ?int
    {
        $w = DB::table('websites')->where('id', $websiteId)->where('workspace_id', $wsId)->whereNull('deleted_at')->first();
        if (! $w || (string) $w->status !== 'published') { return null; }
        if (! empty($w->business_id) && static::where('workspace_id', $wsId)->where('id', $w->business_id)->exists()) { return (int) $w->business_id; }
        $name = trim((string) $w->name) ?: ('Website ' . $websiteId);
        $industry = trim(str_replace('_', ' ', (string) ($w->template_industry ?? '')));
        $isFirst = ! static::where('workspace_id', $wsId)->where('is_default', true)->exists();
        $b = new static([
            'workspace_id' => $wsId, 'name' => mb_substr($name, 0, 160), 'slug' => static::slugFor($wsId, $name),
            'industry' => $industry !== '' ? mb_substr($industry, 0, 120) : null,
            'location' => DB::table('workspaces')->where('id', $wsId)->value('location'),
            'is_default' => $isFirst, 'sort_order' => (int) static::where('workspace_id', $wsId)->max('sort_order') + 1,
        ]);
        $isFirst ? $b->save() : $b->saveQuietly();     // only the default mirrors onto workspaces.*
        DB::table('websites')->where('id', $websiteId)->update(['business_id' => $b->id]);
        return (int) $b->id;
    }

    /** The website is being deleted: soft-delete its profile; if it was the default, the oldest remaining becomes default. */
    public static function retireForWebsite(int $wsId, int $websiteId): void
    {
        $bizId = (int) (DB::table('websites')->where('id', $websiteId)->value('business_id') ?? 0);
        if ($bizId <= 0) { return; }
        $b = static::where('workspace_id', $wsId)->where('id', $bizId)->first();
        if (! $b) { return; }
        DB::table('websites')->where('id', $websiteId)->update(['business_id' => null]);
        $wasDefault = (bool) $b->is_default;
        $b->delete();
        if ($wasDefault) {
            $next = static::where('workspace_id', $wsId)->orderBy('id')->first();
            if ($next) { $next->is_default = true; $next->save(); }   // save (not quiet) so the new default mirrors
        }
    }

    /**
     * RFC-0011 U5a: a website belongs to ONE business — the one named on creation when it is this workspace's, else the
     * default. Returns the business id written (null when the workspace has no businesses yet).
     */
    public static function stampWebsite(int $wsId, int $websiteId, ?int $businessId = null): ?int
    {
        $b = null;
        if ($businessId) { $b = static::where('workspace_id', $wsId)->where('id', $businessId)->first(); }
        if (! $b) { $b = static::where('workspace_id', $wsId)->where('is_default', true)->first(); }
        if (! $b) { return null; }
        DB::table('websites')->where('id', $websiteId)->where('workspace_id', $wsId)->update(['business_id' => $b->id]);
        return (int) $b->id;
    }

    /** A slug unique within the workspace. */
    public static function slugFor(int $wsId, string $name, ?int $ignoreId = null): string
    {
        $base = Str::slug($name) ?: 'business'; $slug = $base; $n = 2;
        while (static::withTrashed()->where('workspace_id', $wsId)->where('slug', $slug)->when($ignoreId, fn ($q) => $q->where('id', '!=', $ignoreId))->exists()) { $slug = $base . '-' . $n++; }
        return $slug;
    }

    /**
     * The write-through mirror: the default business's profile fields are copied onto workspaces.* (no model events,
     * so nothing loops), only where a value differs.
     */
    public function mirrorToWorkspace(): void
    {
        $ws = DB::table('workspaces')->where('id', $this->workspace_id)->first();
        if (! $ws) { return; }
        $upd = [];
        foreach (self::MIRROR as $wsCol => $bCol) {
            $val = $this->{$bCol};
            if ($bCol === 'services_json') {
                $new = is_array($val) ? $val : (is_string($val) ? (json_decode($val, true) ?? []) : []);
                $cur = is_string($ws->$wsCol ?? null) ? (json_decode($ws->$wsCol, true) ?? []) : [];
                if ($cur != $new) { $upd[$wsCol] = json_encode($new, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); }
                continue;
            }
            if ((string) ($ws->$wsCol ?? '') !== (string) ($val ?? '')) { $upd[$wsCol] = $val; }
        }
        if ($upd) { $upd['updated_at'] = now(); DB::table('workspaces')->where('id', $this->workspace_id)->update($upd); }
    }

    /** The reverse mirror: a workspace whose profile columns were written (Settings, onboarding) updates its default business. */
    public static function syncDefaultFromWorkspace(int $wsId): void
    {
        $b = static::where('workspace_id', $wsId)->where('is_default', true)->first();
        if (! $b) { return; }
        $ws = DB::table('workspaces')->where('id', $wsId)->first();
        if (! $ws) { return; }
        $changed = false;
        foreach (self::MIRROR as $wsCol => $bCol) {
            $val = $ws->$wsCol ?? null;
            if ($bCol === 'services_json') {
                $val = is_string($val) ? (json_decode($val, true) ?? []) : (is_array($val) ? $val : []);
                if (($b->services_json ?? []) != $val) { $b->services_json = $val; $changed = true; }
                continue;
            }
            if ($bCol === 'name' && trim((string) $val) === '') { continue; } // an empty business_name never blanks the business
            if ((string) ($b->$bCol ?? '') !== (string) ($val ?? '')) { $b->$bCol = $val; $changed = true; }
        }
        if ($changed) { $b->saveQuietly(); } // quiet: workspaces.* already carries these values
    }
}
