#!/bin/bash
# App shell bundle (perf lever 2, 2026-09-21, EV-1087). The `defer` boot scripts of public/app/index.html are served as
# ONE minified file, js/app.bundle.js, in the order listed in js/app.bundle.list. The 4 sync scripts (auth-refresh,
# launch-scope, website-context, website-scope-bridge) stay separate: inline scripts in index.html run at parse time and
# need them first. Lazy engines (seo, crm, write, studio, projects, social, calendar, infrastructure) are not bundled.
#
#   RUN THIS AFTER EVERY EDIT TO A LISTED FILE — bumping a file's own ?v= no longer ships it. The bundle's ?v= is a content
#   hash and this script rewrites the include line in index.html. To add a boot script: append it to js/app.bundle.list.
#   Minified PER FILE with esbuild: the concatenation cannot be minified as one unit (a duplicate global across two files
#   is legal in classic scripts but a duplicate-symbol error in one module); esbuild keeps top-level names when it is
#   not bundling (verified 2026-09-21: LuAPI, nav, currentView, loadAgentStats, wsLoadSites … all present).
#   Revert: bash build-bundle.sh --revert   (restores the individual tags from js/app.bundle.tags)
set -e
A=/var/www/levelup-staging/public/app
ESB=/var/www/levelup-staging/node_modules/.bin/esbuild
cd "$A"
if [ "$1" = "--revert" ]; then
  python3 - <<'PY'
import re
p='/var/www/levelup-staging/public/app/index.html'; s=open(p,encoding='utf-8').read()
tags=open('/var/www/levelup-staging/public/app/js/app.bundle.tags',encoding='utf-8').read()
s2=re.sub(r'<!-- LU-BUNDLE -->.*?<!-- /LU-BUNDLE -->\n?', tags, s, count=1, flags=re.S)
assert s2!=s, 'no bundle include found'
open(p,'w',encoding='utf-8').write(s2); print('reverted to individual tags')
PY
  exit 0
fi
[ -f js/app.bundle.list ] || { echo "js/app.bundle.list missing"; exit 1; }
OUT=js/app.bundle.js; TMP=js/.app.bundle.tmp; MIN=js/.app.bundle.min
rm -rf "$MIN"; mkdir -p "$MIN"
# a leading statement so no file's 'use strict' prologue can become a directive for the whole bundle (files that were
# strict stay strict inside their own IIFEs; nothing that was sloppy becomes strict)
{ echo "/* LevelUpGrowth app shell bundle — generated by build-bundle.sh $(date -u +%Y-%m-%dT%H:%MZ); do not edit, edit the files in js/app.bundle.list */"; echo "var __luBundle = 1;"; } > "$TMP"
while read -r f; do
  [ -z "$f" ] && continue
  [ -f "js/$f" ] || { echo "missing js/$f"; rm -rf "$TMP" "$MIN"; exit 1; }
  node -e "new Function(require('fs').readFileSync('js/$f','utf8'))" || { echo "syntax error in js/$f"; rm -rf "$TMP" "$MIN"; exit 1; }
  "$ESB" "js/$f" --minify --target=es2018 --legal-comments=none --outfile="$MIN/$f" --log-level=error || { echo "minify failed js/$f"; rm -rf "$TMP" "$MIN"; exit 1; }
  { echo; echo ";/* -- js/$f -- */;"; cat "$MIN/$f"; echo; echo ";"; } >> "$TMP"
done < js/app.bundle.list
rm -rf "$MIN"
node -e "new Function(require('fs').readFileSync('$TMP','utf8'))" || { echo "bundle syntax error"; rm -f "$TMP"; exit 1; }
mv "$TMP" "$OUT"
H=$(sha1sum "$OUT" | cut -c1-10)
python3 - "$H" <<'PY'
import re, sys
h=sys.argv[1]; p='/var/www/levelup-staging/public/app/index.html'; s=open(p,encoding='utf-8').read()
inc='<!-- LU-BUNDLE --><script defer src="/app/js/app.bundle.js?v=%s"></script><!-- /LU-BUNDLE -->\n' % h
if '<!-- LU-BUNDLE -->' in s:
    s=re.sub(r'<!-- LU-BUNDLE -->.*?<!-- /LU-BUNDLE -->\n?', inc, s, count=1, flags=re.S)
else:
    files=[l.strip() for l in open('/var/www/levelup-staging/public/app/js/app.bundle.list') if l.strip()]
    tags=[]; first=None
    for f in files:
        m=re.search(r'<script defer src="/app/js/%s\?v=[^"]*"></script>\n' % re.escape(f), s)
        assert m, f
        tags.append(m.group(0))
        if first is None: first=m.start()
    open('/var/www/levelup-staging/public/app/js/app.bundle.tags','w',encoding='utf-8').write(''.join(tags))
    for t in tags: s=s.replace(t,'',1)
    s=s[:first]+inc+s[first:]
open(p,'w',encoding='utf-8').write(s); print('index.html include ->', h)
PY
ls -la "$OUT" | awk '{print $5" bytes"}'
